package main

var embeddedTable = []DBLine{
{ID: 1, English: "I see.", Chinese: "我明白了。"},
{ID: 2, English: "I quit!", Chinese: "我不幹了!"},
{ID: 3, English: "Let go!", Chinese: "放手!"},
{ID: 4, English: "Me too.", Chinese: "我也是。"},
{ID: 5, English: "My god!", Chinese: "天哪!"},
{ID: 6, English: "No way!", Chinese: "不行!"},
{ID: 7, English: "Come on.", Chinese: "來吧(趕快)"},
{ID: 8, English: "Hold on.", Chinese: "等一等。"},
{ID: 9, English: "I agree.", Chinese: "我同意。"},
{ID: 10, English: "Not bad.", Chinese: "還不錯。"},
{ID: 11, English: "Not yet.", Chinese: "還沒。"},
{ID: 12, English: "See you.", Chinese: "再見。"},
{ID: 13, English: "Shut up!", Chinese: "閉嘴!"},
{ID: 14, English: "So long.", Chinese: "再見。"},
{ID: 15, English: "Why not?", Chinese: "好呀! (為什麼不呢?)"},
{ID: 16, English: "Allow me.", Chinese: "讓我來。"},
{ID: 17, English: "Be quiet!", Chinese: "安靜點!"},
{ID: 18, English: "Cheer up!", Chinese: "振作起來!"},
{ID: 19, English: "Good job!", Chinese: "做得好!"},
{ID: 20, English: "Have fun!", Chinese: "玩得開心!"},
{ID: 21, English: "How much?", Chinese: "多少錢?"},
{ID: 22, English: "I'm full.", Chinese: "我飽了。"},
{ID: 23, English: "I'm home.", Chinese: "我回來了。"},
{ID: 24, English: "I'm lost.", Chinese: "我迷路了。"},
{ID: 25, English: "My treat.", Chinese: "我請客。"},
{ID: 26, English: "So do I.", Chinese: "我也一樣。"},
{ID: 27, English: "This way.", Chinese: "這邊請。"},
{ID: 28, English: "After you.", Chinese: "您先。"},
{ID: 29, English: "Bless you!", Chinese: "祝福你!"},
{ID: 30, English: "Follow me.", Chinese: "跟我來。"},
{ID: 31, English: "Forget it!", Chinese: "休想! (算了!)"},
{ID: 32, English: "Good luck!", Chinese: "祝好運!"},
{ID: 33, English: "I decline!", Chinese: "我拒絕!"},
{ID: 34, English: "I promise.", Chinese: "我保證。"},
{ID: 35, English: "Of course!", Chinese: "當然了!"},
{ID: 36, English: "Slow down!", Chinese: "慢點!"},
{ID: 37, English: "Take care!", Chinese: "保重!"},
{ID: 38, English: "They hurt.", Chinese: "(傷口)疼。"},
{ID: 39, English: "Try again.", Chinese: "再試試。"},
{ID: 40, English: "Watch out!", Chinese: "當心。"},
{ID: 41, English: "What's up?", Chinese: "有什麼事嗎?"},
{ID: 42, English: "Be careful!", Chinese: "注意!"},
{ID: 43, English: "Bottoms up!", Chinese: "乾杯 (見底)!"},
{ID: 44, English: "Don't move!", Chinese: "不許動!"},
{ID: 45, English: "Guess what?", Chinese: "猜猜看?"},
{ID: 46, English: "I doubt it.", Chinese: "我懷疑。"},
{ID: 47, English: "I think so.", Chinese: "我也這麼想。"},
{ID: 48, English: "I'm single.", Chinese: "我是單身貴族。"},
{ID: 49, English: "Keep it up!", Chinese: "堅持下去!"},
{ID: 50, English: "Let me see.", Chinese: "讓我想想。"},
{ID: 51, English: "Never mind.", Chinese: "不要緊。"},
{ID: 52, English: "No problem!", Chinese: "沒問題!"},
{ID: 53, English: "That's all!", Chinese: "就這樣!"},
{ID: 54, English: "Time is up.", Chinese: "時間快到了。"},
{ID: 55, English: "What's new?", Chinese: "有什麼新鮮事嗎?"},
{ID: 56, English: "Count me on.", Chinese: "算我一份。"},
{ID: 57, English: "Don't worry.", Chinese: "別擔心。"},
{ID: 58, English: "Feel better?", Chinese: "好點了嗎?"},
{ID: 59, English: "I love you!", Chinese: "我愛你!"},
{ID: 60, English: "I'm his fan.", Chinese: "我是他的影迷。"},
{ID: 61, English: "Is it yours?", Chinese: "這是你的嗎?"},
{ID: 62, English: "That's neat.", Chinese: "這很好。"},
{ID: 63, English: "Are you sure?", Chinese: "你肯定嗎?"},
{ID: 64, English: "Do l have to?", Chinese: "非做不可嗎?"},
{ID: 65, English: "He is my age.", Chinese: "他和我同歲。"},
{ID: 66, English: "Here you are.", Chinese: "給你。"},
{ID: 67, English: "No one knows.", Chinese: "沒有人知道。"},
{ID: 68, English: "Take it easy.", Chinese: "別緊張。"},
{ID: 69, English: "What a pity!", Chinese: "太遺憾了!"},
{ID: 70, English: "Any thing else?", Chinese: "還要別的嗎?"},
{ID: 71, English: "To be careful!", Chinese: "一定要小心!"},
{ID: 72, English: "Do me a favor?", Chinese: "幫個忙,好嗎?"},
{ID: 73, English: "Help yourself.", Chinese: "(請用 或 自己來) 別客氣。"},
{ID: 74, English: "I'm on a diet.", Chinese: "我在節食。"},
{ID: 75, English: "Keep in Touch.", Chinese: "保持聯絡。"},
{ID: 76, English: "Time is money.", Chinese: "時間就是金錢。"},
{ID: 77, English: "Who's calling?", Chinese: "是哪一位?"},
{ID: 78, English: "You did right.", Chinese: "你做得對。"},
{ID: 79, English: "You set me up!", Chinese: "你出賣我!"},
{ID: 80, English: "Can I help you?", Chinese: "我能幫你嗎?"},
{ID: 81, English: "Enjoy yourself!", Chinese: "祝你玩得開心!"},
{ID: 82, English: "Excuse me, Sir.", Chinese: "先生,對不起。"},
{ID: 83, English: "Give me a hand!", Chinese: "幫幫我!"},
{ID: 84, English: "How's it going?", Chinese: "怎麼樣?"},
{ID: 85, English: "I have no idea.", Chinese: "我沒有頭緒。"},
{ID: 86, English: "I just made it!", Chinese: "我做到了!"},
{ID: 87, English: "I'll see to it.", Chinese: "我會留意的。"},
{ID: 88, English: "I'm in a hurry!", Chinese: "我在趕時間!"},
{ID: 89, English: "It's her field.", Chinese: "這是她的本行。"},
{ID: 90, English: "It's up to you.", Chinese: "由你決定。"},
{ID: 91, English: "Just wonderful!", Chinese: "簡直太棒了!"},
{ID: 92, English: "What about you?", Chinese: "你呢?"},
{ID: 93, English: "You owe me one.", Chinese: "你欠我一個人情。"},
{ID: 94, English: "You're welcome.", Chinese: "不客氣。"},
{ID: 95, English: "Any day will do.", Chinese: "哪一天都行"},
{ID: 96, English: "Are you kidding?", Chinese: "你在開玩笑吧!"},
{ID: 97, English: "Congratulations!", Chinese: "祝賀你!"},
{ID: 98, English: "I can't help it.", Chinese: "我情不自禁。"},
{ID: 99, English: "I didn't mean it.", Chinese: "我不是故意的。"},
{ID: 100, English: "I'll fix you up.", Chinese: "我會幫你打點的。"},
{ID: 101, English: "It sounds great!", Chinese: "聽起來很不錯。"},
{ID: 102, English: "It's a fine day.", Chinese: "今天是個好天。"},
{ID: 103, English: "So far, So good.", Chinese: "目前還不錯。"},
{ID: 104, English: "What time is it?", Chinese: "幾點了?"},
{ID: 105, English: "You can make it!", Chinese: "你能做到!"},
{ID: 106, English: "Control yourself!", Chinese: "克制一下!"},
{ID: 107, English: "He came by train.", Chinese: "他乘火車來。"},
{ID: 108, English: "He is ill in bed.", Chinese: "他臥病在床。"},
{ID: 109, English: "He lacks courage.", Chinese: "他缺乏勇氣。"},
{ID: 110, English: "How's everything?", Chinese: "一切還好吧?"},
{ID: 111, English: "I have no choice.", Chinese: "我別無選擇。"},
{ID: 112, English: "I like ice-cream.", Chinese: "我喜歡吃冰淇淋。"},
{ID: 113, English: "I love this game.", Chinese: "我鍾愛這項運動。"},
{ID: 114, English: "I'll try my best.", Chinese: "我盡力而為。"},
{ID: 115, English: "I'm on your side.", Chinese: "我全力支援你。"},
{ID: 116, English: "Long time no see!", Chinese: "好久不見!"},
{ID: 117, English: "No pain, no gain.", Chinese: "不勞無穫。"},
{ID: 118, English: "Well, it depends.", Chinese: "噢,這得看情況。"},
{ID: 119, English: "We're all for it.", Chinese: "我們全都同意。"},
{ID: 120, English: "What a good deal!", Chinese: "真便宜!"},
{ID: 121, English: "What should I do?", Chinese: "我該怎麼辦？"},
{ID: 122, English: "You asked for it!", Chinese: "你自討苦吃!"},
{ID: 123, English: "You have my word.", Chinese: "我保證。"},
{ID: 124, English: "Believe it or not!", Chinese: "信不信由你!"},
{ID: 125, English: "Don't count on me.", Chinese: "別指望我。"},
{ID: 126, English: "Don't fall for it!", Chinese: "別上當!"},
{ID: 127, English: "Don't let me down.", Chinese: "別讓我失望。"},
{ID: 128, English: "Easy come easy go.", Chinese: "來得容易，去得快。"},
{ID: 129, English: "I beg your pardon.", Chinese: "請你原諒。"},
{ID: 130, English: "I beg your pardon?", Chinese: "請您再說一遍(我沒有聽清楚)。"},
{ID: 131, English: "I'll be back soon.", Chinese: "我馬上回來。"},
{ID: 132, English: "I'll check it out.", Chinese: "我去查查看。"},
{ID: 133, English: "It’s a long story.", Chinese: "說來話長。"},
{ID: 134, English: "It’s Sunday today.", Chinese: "今天是星期天。"},
{ID: 135, English: "Just wait and see!", Chinese: "等著瞧!"},
{ID: 136, English: "Make up your mind.", Chinese: "做個決定吧。"},
{ID: 137, English: "That's all I need.", Chinese: "我就要這些。"},
{ID: 138, English: "The view is great.", Chinese: "景色多麼漂亮!"},
{ID: 139, English: "The wall has ears.", Chinese: "隔牆有耳。"},
{ID: 140, English: "There comes a bus.", Chinese: "汽車來了。"},
{ID: 141, English: "What day is today?", Chinese: "今天星期幾?"},
{ID: 142, English: "What do you think?", Chinese: "你怎麼認為？"},
{ID: 143, English: "Who told you that?", Chinese: "誰告訴你的?"},
{ID: 144, English: "Who's kicking off?", Chinese: "現在是誰在開球?"},
{ID: 145, English: "Yes,I suppose So.", Chinese: "是的,我也這麼認為。"},
{ID: 146, English: "You can't miss it", Chinese: "你一定能找到的。"},
{ID: 147, English: "Any messages for me?", Chinese: "有我的留言嗎?"},
{ID: 148, English: "Don't be so modest.", Chinese: "別謙虛了。"},
{ID: 149, English: "Don't give me that!", Chinese: "少來這套!"},
{ID: 150, English: "He is a smart boy.", Chinese: "他是個小機靈鬼。"},
{ID: 151, English: "He is just a child.", Chinese: "他只是個孩子。"},
{ID: 152, English: "I can't follow you.", Chinese: "我不懂你說的。"},
{ID: 153, English: "I felt sort of ill.", Chinese: "我感覺有點不適。"},
{ID: 154, English: "I have a good idea!", Chinese: "我有一個好主意。"},
{ID: 155, English: "It is growing cool.", Chinese: "天氣漸漸涼爽起來。"},
{ID: 156, English: "It seems all right.", Chinese: "看來這沒問題。"},
{ID: 157, English: "It's going too far.", Chinese: "太離譜了。"},
{ID: 158, English: "May I use your pen?", Chinese: "我可以用你的筆嗎?"},
{ID: 159, English: "She had a bad cold.", Chinese: "她患了重感冒。"},
{ID: 160, English: "That's a good idea.", Chinese: "這個主意真不錯。"},
{ID: 161, English: "The answer is zero.", Chinese: "白忙了。"},
{ID: 162, English: "What does she like?", Chinese: "她喜歡什麼?"},
{ID: 163, English: "As soon as possible!", Chinese: "越快越好!"},
{ID: 164, English: "He cans hardly speak.", Chinese: "他幾乎說不出話來。"},
{ID: 165, English: "He always talks big.", Chinese: "他總是吹牛。"},
{ID: 166, English: "He won an election.", Chinese: "他在選舉中獲勝。"},
{ID: 167, English: "I am a football fan.", Chinese: "我是個足球迷。"},
{ID: 168, English: "If only I could fly.", Chinese: "要是我能飛就好了。"},
{ID: 169, English: "I'll be right there.", Chinese: "我馬上就到。"},
{ID: 170, English: "I'll see you at six.", Chinese: "我六點鐘見你。"},
{ID: 171, English: "Is it true or false?", Chinese: "這是對的還是錯的?"},
{ID: 172, English: "Just read it for me.", Chinese: "就讀給我聽好了。"},
{ID: 173, English: "Knowledge is power.", Chinese: "知識就是力量。"},
{ID: 174, English: "Move out of my way!", Chinese: "讓開!"},
{ID: 175, English: "Time is running out.", Chinese: "沒時間了。"},
{ID: 176, English: "We are good friends.", Chinese: "我們是好朋友。"},
{ID: 177, English: "What's your trouble?", Chinese: "你哪兒不舒服?"},
{ID: 178, English: "You did fairly well!", Chinese: "你幹得相當不錯!"},
{ID: 179, English: "Clothes make the man.", Chinese: "人要衣裝。"},
{ID: 180, English: "Did you miss the bus?", Chinese: "你錯過公共汽車了?"},
{ID: 181, English: "Don't lose your head。", Chinese: "不要驚慌失措。"},
{ID: 182, English: "He can't take a joke.", Chinese: "他開不得玩笑。"},
{ID: 183, English: "He owes my uncle $100", Chinese: "他欠我叔叔100美元。"},
{ID: 184, English: "How are things going?", Chinese: "事情進展得怎樣?"},
{ID: 185, English: "How are you recently?", Chinese: "最近怎麼樣?"},
{ID: 186, English: "I know all about it.", Chinese: "我知道有關它的一切。"},
{ID: 187, English: "It really takes time.", Chinese: "這樣太耽誤時間了。"},
{ID: 188, English: "It's against the law.", Chinese: "這是違法的。"},
{ID: 189, English: "Love me, love my dog.", Chinese: "(諺語)愛屋及烏。"},
{ID: 190, English: "My mouth is watering.", Chinese: "我要流口水了。"},
{ID: 191, English: "Speak louder, please.", Chinese: "說話請大聲點兒。"},
{ID: 192, English: "This boy has no job.", Chinese: "這個男孩沒有工作。"},
{ID: 193, English: "This house is my own.", Chinese: "這所房子是我自己的。"},
{ID: 194, English: "What happened to you?", Chinese: "你怎麼了?"},
{ID: 195, English: "You are just in time.", Chinese: "你來得正是時候。"},
{ID: 196, English: "You need to workout.", Chinese: "你需要去運動鍛鍊一下。"},
{ID: 197, English: "Your hand feels cold.", Chinese: "你的手摸起來很冷。。"},
{ID: 198, English: "Don't be so childish.", Chinese: "別這麼孩子氣。"},
{ID: 199, English: "Don't trust the chance!", Chinese: "不要碰運氣。"},
{ID: 200, English: "Fasten your seat belt.", Chinese: "繫好你的安全帶。"},
{ID: 201, English: "He has a large income.", Chinese: "他有很高的收入。"},
{ID: 202, English: "He looks very healthy.", Chinese: "他看來很健康。"},
{ID: 203, English: "He paused for a reply.", Chinese: "他停下來等著回答。"},
{ID: 204, English: "He repaired his house.", Chinese: "他修理了他的房子。"},
{ID: 205, English: "He suggested a picnic.", Chinese: "他建議搞一次野餐。"},
{ID: 206, English: "Here's a gift for you.", Chinese: "這裡有個禮物送給你。"},
{ID: 207, English: "How much does it cost?", Chinese: "多少錢?"},
{ID: 208, English: "I caught the last bus.", Chinese: "我趕上了最後一班車。"},
{ID: 209, English: "I could hardly speak.", Chinese: "我簡直說不出話來。"},
{ID: 210, English: "I'll have to try that.", Chinese: "我得試試這麼做。"},
{ID: 211, English: "I'm very proud of you.", Chinese: "我為你感到非常驕傲。"},
{ID: 212, English: "It doesn't make sense.", Chinese: "這沒有意義(不合常理)。"},
{ID: 213, English: "Make yourself at home.", Chinese: "請不要拘禮。"},
{ID: 214, English: "My car needs washing.", Chinese: "我的車需要洗一洗。"},
{ID: 215, English: "None of your business!", Chinese: "與你無關!"},
{ID: 216, English: "Not a sound was heard.", Chinese: "一點聲音也沒有。"},
{ID: 217, English: "That's always the case.", Chinese: "習以為常了。"},
{ID: 218, English: "The road divides here.", Chinese: "這條路在這裡分岔。"},
{ID: 219, English: "Those are watermelons.", Chinese: "那些是西瓜。"},
{ID: 220, English: "What a nice day it is!", Chinese: "今天天氣真好!"},
{ID: 221, English: "What's wrong with you?", Chinese: "你哪不對勁?"},
{ID: 222, English: "You are a chicken.", Chinese: "你是個膽小鬼。"},
{ID: 223, English: "A lovely day, isn't it?", Chinese: "好天氣,是嗎?"},
{ID: 224, English: "He is collecting money.", Chinese: "他在籌集資金。"},
{ID: 225, English: "He was born in New York.", Chinese: "他出生在紐約。"},
{ID: 226, English: "He was not a bit tired.", Chinese: "他一點也不累。"},
{ID: 227, English: "I will be more careful.", Chinese: "我會小心一些的,"},
{ID: 228, English: "I will never forget it.", Chinese: "我會記著的。"},
{ID: 229, English: "It is just what I need.", Chinese: "這正是我所需要的。"},
{ID: 230, English: "It rather surprised me.", Chinese: "那事使我頗感驚訝。"},
{ID: 231, English: "Just around the comer.", Chinese: "就在附近。"},
{ID: 232, English: "Just for entertainment.", Chinese: "只是為了消遣一下。"},
{ID: 233, English: "Let bygones be bygones.", Chinese: "過去的,就讓它過去吧。"},
{ID: 234, English: "Mother doesn't make up.", Chinese: "媽媽不化妝。"},
{ID: 235, English: "Oh, you are kidding me.", Chinese: "哦, 你別拿我開玩笑了。"},
{ID: 236, English: "She has been to school.", Chinese: "她上學去了。"},
{ID: 237, English: "Skating is interesting.", Chinese: "滑冰很有趣。"},
{ID: 238, English: "Supper is ready at six.", Chinese: "晚餐六點鐘就好了。"},
{ID: 239, English: "That's a terrific idea!", Chinese: "真是好主意!"},
{ID: 240, English: "What horrible weather!", Chinese: "這鬼天氣!"},
{ID: 241, English: "Which would you prefer?", Chinese: "你要選哪個?"},
{ID: 242, English: "Does she like ice cream?", Chinese: "她喜歡吃冰淇淋嗎?"},
{ID: 243, English: "First come first served.", Chinese: "先到先得。"},
{ID: 244, English: "Great minds think alike.", Chinese: "英雄所見略同。"},
{ID: 245, English: "He has a sense of humor.", Chinese: "他有幽默感。"},
{ID: 246, English: "He is acting an old man.", Chinese: "他正扮演一個老人。"},
{ID: 247, English: "He is looking for a job.", Chinese: "他正在找工作。"},
{ID: 248, English: "He doesn't care about me.", Chinese: "他並不在乎我。"},
{ID: 249, English: "I develop films myself.", Chinese: "我自己沖洗照片。"},
{ID: 250, English: "I felt no regret for it.", Chinese: "對這件事我不覺得後悔。"},
{ID: 251, English: "I get up at six o'clock.", Chinese: "我六點起床。"},
{ID: 252, English: "I meet the boss himself.", Chinese: "我見到了老闆本人。"},
{ID: 253, English: "I owe you for my dinner.", Chinese: "我欠你晚餐的錢。"},
{ID: 254, English: "I really enjoyed myself.", Chinese: "我玩得很開心。"},
{ID: 255, English: "I'm fed up with my work!", Chinese: "我對工作煩死了!"},
{ID: 256, English: "It's no use complaining.", Chinese: "發牢騷沒什麼用。"},
{ID: 257, English: "She's under the weather.", Chinese: "她心情不好。"},
{ID: 258, English: "The child sobbed sadly.", Chinese: "小孩傷心地抽泣著。"},
{ID: 259, English: "The rumor had no basis.", Chinese: "那謠言沒有根據。"},
{ID: 260, English: "They praised him highly.", Chinese: "他們大大地表揚了他。"},
{ID: 261, English: "Winter is a cold season.", Chinese: "冬天是一個,寒冷的季節。"},
{ID: 262, English: "You can call me any time.", Chinese: "你可以隨時打電話給我。"},
{ID: 263, English: "15 divided by 3 equals 5.", Chinese: "15除以3等於5。"},
{ID: 264, English: "All for one, one for all.", Chinese: "我為人人，人人為我。"},
{ID: 265, English: "East, west, home is best.", Chinese: "金窩，銀窩，不如自己的草窩。"},
{ID: 266, English: "He grasped both my hands.", Chinese: "他緊握住我的雙手。"},
{ID: 267, English: "He is physically mature.", Chinese: "他身體己發育成熟。"},
{ID: 268, English: "I am so sorry about this.", Chinese: "對此我非常抱歉(遺憾)。"},
{ID: 269, English: "I can't afford a new car.", Chinese: "我買不起一部新車。"},
{ID: 270, English: "I do want to see him now.", Chinese: "我現在確實很想去見他。"},
{ID: 271, English: "I have the right to know.", Chinese: "我有權知道。"},
{ID: 272, English: "I heard someone laughing.", Chinese: "我聽見有人在笑。"},
{ID: 273, English: "I suppose you dance much.", Chinese: "我想你常常跳舞吧。"},
{ID: 274, English: "I walked across the park.", Chinese: "我穿過了公園。"},
{ID: 275, English: "I'll just play it by ear.", Chinese: "我到時隨機應變。"},
{ID: 276, English: "I'm not sure I can do it.", Chinese: "恐怕這事我幹不了。"},
{ID: 277, English: "I'm not used to drinking.", Chinese: "我不習慣喝酒。"},
{ID: 278, English: "Is the cut still sore?", Chinese: "傷口還在痛嗎?"},
{ID: 279, English: "It's too good to be true!", Chinese: "好得難以置信。"},
{ID: 280, English: "Jean is a blue-eyed girl.", Chinese: "珍是個藍眼睛的女孩。"},
{ID: 281, English: "Let's not waste our time.", Chinese: "咱們別浪費時間了。"},
{ID: 282, English: "May I ask some questions?", Chinese: "我可以問幾個問題嗎?"},
{ID: 283, English: "Money is not everything.", Chinese: "金錢不是一切。"},
{ID: 284, English: "Neither of the men spoke.", Chinese: "兩個人都沒說過話。"},
{ID: 285, English: "Stop making such a noise.", Chinese: "別吵了。"},
{ID: 286, English: "That makes no difference.", Chinese: "沒什麼區別。"},
{ID: 287, English: "The price is reasonable.", Chinese: "價格還算合理。"},
{ID: 288, English: "They crowned him king.", Chinese: "他們擁立他為國王。"},
{ID: 289, English: "They're in red and white.", Chinese: "他們穿著紅白相間的衣服。"},
{ID: 290, English: "We all desire happiness.", Chinese: "我們都想要幸福。"},
{ID: 291, English: "We just caught the plane", Chinese: "我們剛好趕上了飛機。"},
{ID: 292, English: "What shall we do tonight?", Chinese: "我們今天晚上去幹點兒什麼呢?"},
{ID: 293, English: "What's your goal in life", Chinese: "你的人生目標是什麼?"},
{ID: 294, English: "When was the house built?", Chinese: "這幢房子是什麼時候建造的?"},
{ID: 295, English: "Why did you stay at home?", Chinese: "為什麼呆在家裏?"},
{ID: 296, English: "Would you like some help?", Chinese: "今天真漂亮!"},
{ID: 297, English: "You mustn't aim too high", Chinese: "你不可好高騖遠。"},
{ID: 298, English: "You're really killing me!", Chinese: "真是笑死我了!"},
{ID: 299, English: "You've got a point there.", Chinese: "你說得挺有道理的。"},
{ID: 300, English: "Being criticized is awful!", Chinese: "被人批評真是痛苦!"},
{ID: 301, English: "Did you enter the contest?", Chinese: "你參加比賽了嗎?"},
{ID: 302, English: "Do you accept credit cards?", Chinese: "你們收信用卡嗎?"},
{ID: 303, English: "Don't cry over spilt milk.", Chinese: "不要做無益的後悔。"},
{ID: 304, English: "Don't let chances pass by.", Chinese: "不要讓機遇從我們身邊溜走。"},
{ID: 305, English: "He owned himself defeated.", Chinese: "他承認自己失敗了。"},
{ID: 306, English: "He seems a little nervous.", Chinese: "他顯得有點緊張。"},
{ID: 307, English: "He strolls about the town.", Chinese: "他在鎮上四處遛達。"},
{ID: 308, English: "Her tooth ached all night.", Chinese: "她牙疼了一整夜。"},
{ID: 309, English: "How about a drink tonight?", Chinese: "今晚喝一杯怎樣?"},
{ID: 310, English: "I can do nothing but that.", Chinese: "我只會做那件事。"},
{ID: 311, English: "I get hold of you at last.", Chinese: "我終於找到你了。"},
{ID: 312, English: "I have a surprise for you.", Chinese: "我有一個意想不到的東西給你看。"},
{ID: 313, English: "I like all kinds of fruit.", Chinese: "我喜歡各種各樣的水果。"},
{ID: 314, English: "I saw it with my own eyes.", Chinese: "我親眼所見。"},
{ID: 315, English: "I will arrange everything.", Chinese: "我會安排一切的。"},
{ID: 316, English: "I wish I knew my neighbor.", Chinese: "我很想認識我的鄰居。"},
{ID: 317, English: "I would like to check out.", Chinese: "我想結帳。"},
{ID: 318, English: "It has become much cooler.", Chinese: "天氣變得涼爽多了。"},
{ID: 319, English: "It's time you went to bed.", Chinese: "你早就該睡覺了。( It’s time for bed.)"},
{ID: 320, English: "No spitting on the street.", Chinese: "禁止在大街上吐痰。"},
{ID: 321, English: "She was totally exhausted.", Chinese: "(She was beat.) 她累垮了。"},
{ID: 322, English: "Show your tickets, please.", Chinese: "請出示你的票。"},
{ID: 323, English: "Thank you for your advice.", Chinese: "謝謝你的建議。"},
{ID: 324, English: "That's the latest fashion.", Chinese: "這是最流行的款式。"},
{ID: 325, English: "The train arrived on time.", Chinese: "火車準時到達。"},
{ID: 326, English: "There go the house lights.", Chinese: "劇院的燈光滅了。"},
{ID: 327, English: "They are paid by the hour.", Chinese: "他們按時取酬。"},
{ID: 328, English: "Things are getting better.", Chinese: "情況正在好轉。"},
{ID: 329, English: "Wake me up at five thirty.", Chinese: "請在五點半叫醒我。"},
{ID: 330, English: "We are all busy with work.", Chinese: "我們都忙於工作。"},
{ID: 331, English: "Where do you want to meet?", Chinese: "你想在哪兒見面?"},
{ID: 332, English: "You can get what you want.", Chinese: "你能得到你想要的。"},
{ID: 333, English: "A barking dog doesn't bite!", Chinese: "吠犬不咬人。"},
{ID: 334, English: "Are you free this Saturday?", Chinese: "你這個星期六有空嗎?"},
{ID: 335, English: "Be careful not to fall ill.", Chinese: "注意不要生病了。"},
{ID: 336, English: "Being a mother is not easy.", Chinese: "做一個母親是不容易的。"},
{ID: 337, English: "Brevity is the soul of wit.", Chinese: "簡潔是智慧的精華。"},
{ID: 338, English: "Cancer is a deadly disease.", Chinese: "癌症是一種致命的疾病。"},
{ID: 339, English: "Did you fight with others?", Chinese: "你又和別人打架了嗎?"},
{ID: 340, English: "Don't dream away your time.", Chinese: "不要虛度光陰。"},
{ID: 341, English: "Don't keep me waiting long.", Chinese: "不要讓我等得太久。"},
{ID: 342, English: "He has a remarkable memory.", Chinese: "他有驚人的記憶力。"},
{ID: 343, English: "He has completed the task.", Chinese: "他完成了這個任務。"},
{ID: 344, English: "He has quite a few friends.", Chinese: "他有不少的朋友。"},
{ID: 345, English: "He is capable of any crime.", Chinese: "他什麼樣的壞事都能幹得出來。"},
{ID: 346, English: "He walks with a quick pace.", Chinese: "他快步走路。"},
{ID: 347, English: "He was not a little tired.", Chinese: "他很累。"},
{ID: 348, English: "His looks are always funny.", Chinese: "他的樣子總是滑稽可笑。"},
{ID: 349, English: "How about going to a movie?", Chinese: "去看場電影怎麼樣?"},
{ID: 350, English: "I think I've caught a cold.", Chinese: "我想我得了感冒。"},
{ID: 351, English: "I was taking care of Sally.", Chinese: "我在照顧莎莉。"},
{ID: 352, English: "I wish I lived in New York.", Chinese: "我希望住在紐約。"},
{ID: 353, English: "I'm very glad to hear that.", Chinese: "很高興聽你這樣說。"},
{ID: 354, English: "I'm your lucky fellow then.", Chinese: "我就是你的幸運舞伴啦!"},
{ID: 355, English: "It's none of your business!", Chinese: "這不關你的事兒!"},
{ID: 356, English: "No littering on the campus.", Chinese: "在校園內不准亂丟廢物。"},
{ID: 357, English: "She is a good-looking girl.", Chinese: "她是一個漂亮女孩。"},
{ID: 358, English: "She mended the broken doll.", Chinese: "她修補了破了的洋娃娃。"},
{ID: 359, English: "So I just take what I want.", Chinese: "那麼我只拿我所需要的東西。"},
{ID: 360, English: "Spring is a pretty season,", Chinese: "春天是一個好季節。"},
{ID: 361, English: "The figure seems all Right.", Chinese: "數目看起來是對的。"},
{ID: 362, English: "The stars are too far away.", Chinese: "星星太遙遠了。"},
{ID: 363, English: "The whole world knows that.", Chinese: "全世界都知道。"},
{ID: 364, English: "Tomorrow will be a holiday.", Chinese: "明天放假。"},
{ID: 365, English: "We walk on the garden path.", Chinese: "我們走在花園小徑上。"},
{ID: 366, English: "What you need is just rest.", Chinese: "你需要的就是休息。"},
{ID: 367, English: "What are your favorite steps?", Chinese: "你最喜歡跳什麼舞?"},
{ID: 368, English: "You'd better let her alone.", Chinese: "你們最好是讓她一個人呆會兒。"},
{ID: 369, English: "A lost chance never returns.", Chinese: "錯過的機會永不再來。"},
{ID: 370, English: "Don't let this get you down.", Chinese: "不要為此灰心喪氣。"},
{ID: 371, English: "He shot the lion with a gun.", Chinese: "他用槍把獅子打死了。"},
{ID: 372, English: "I don't think you are right.", Chinese: "我認為你是不對的。"},
{ID: 373, English: "I have never seen the movie.", Chinese: "我從未看過那部電影。"},
{ID: 374, English: "I haven't seen you for ages.", Chinese: "我好久沒見到你了。"},
{ID: 375, English: "I was alone, but not lonely.", Chinese: "我獨自一人，但並不覺得寂寞。"},
{ID: 376, English: "I went there three days ago.", Chinese: "我三天前去過那兒。"},
{ID: 377, English: "It's a friendly competition.", Chinese: "這是一場友誼賽。"},
{ID: 378, English: "It's very thoughtful of you.", Chinese: "你想得真週到。"},
{ID: 379, English: "May I speak to Lora, please?", Chinese: "我能和勞拉說話嗎?"},
{ID: 380, English: "Mr. Wang is fixing his bike.", Chinese: "王先生在修他的自行車。"},
{ID: 381, English: "My brother is seeking a job.", Chinese: "我弟弟正在找工作。"},
{ID: 382, English: "Nancy will retire next year.", Chinese: "南希明年就退休了。"},
{ID: 383, English: "Neither you nor he is wrong.", Chinese: "你沒錯，他也沒錯。"},
{ID: 384, English: "Opportunity knocks but once.", Chinese: "機不可失，時不再來。"},
{ID: 385, English: "She dressed herself hastily.", Chinese: "她匆忙穿上衣服。"},
{ID: 386, English: "She hired a car by the hour.", Chinese: "她租了一輛按鐘點計費的汽車。"},
{ID: 387, English: "Someone is ringing the bell.", Chinese: "有人在按門鈴。"},
{ID: 388, English: "The Smiths are my neighbors.", Chinese: "史密斯一家是我的鄰居。"},
{ID: 389, English: "These shoes don't fit right.", Chinese: "這雙鞋不太合適。"},
{ID: 390, English: "This is only the first half.", Chinese: "這才是上半場呢。"},
{ID: 391, English: "This pen doesn't write well.", Chinese: "這鋼筆不好寫。"},
{ID: 392, English: "Would you like a cup of tea?", Chinese: "你想喝杯茶嗎?"},
{ID: 393, English: "You really look sharp today.", Chinese: "你今天真漂亮。"},
{ID: 394, English: "Another cat came to my house.", Chinese: "又有一隻貓來到我家了。"},
{ID: 395, English: "Check your answers with mine.", Chinese: "把你的答案跟我的核對一下。"},
{ID: 396, English: "Don't keep the truth from me.", Chinese: "別瞞著我事實真相。"},
{ID: 397, English: "Everything has its beginning.", Chinese: "凡事都有開端。"},
{ID: 398, English: "He came to the point at once.", Chinese: "他一下子就說到了點子上。"},
{ID: 399, English: "He fell behind with his work.", Chinese: "他工作落後了。"},
{ID: 400, English: "He is the happiest man alive.", Chinese: "他是世界上最快樂的人。"},
{ID: 401, English: "He neither smokes nor drinks.", Chinese: "他既不抽煙，也不喝酒。"},
{ID: 402, English: "He ran his horse up the hill.", Chinese: "他策馬跑上小山。"},
{ID: 403, English: "He reminds me of his brother.", Chinese: "他使我想起了他的弟弟。"},
{ID: 404, English: "He was efficient in his work.", Chinese: "他工作效率高。"},
{ID: 405, English: "He will do anything but work.", Chinese: "只要不是幹活,他幹什麼都行。"},
{ID: 406, English: "His father runs a restaurant.", Chinese: "他的父親經營一家餐館。"},
{ID: 407, English: "I have something to tell you.", Chinese: "我有事要告訴你。"},
{ID: 408, English: "I smelled a smell of cooking.", Chinese: "我聞到了燒菜做飯的味道。"},
{ID: 409, English: "I want to see the film again.", Chinese: "我真想再看一遍。"},
{ID: 410, English: "I've got too much work to do.", Chinese: "我要做的工作太多了。"},
{ID: 411, English: "Let's go for a walk, shall we?", Chinese: "咱們出去走走,好嗎?"},
{ID: 412, English: "Please let me check the bill.", Chinese: "請讓我核對一下帳單。"},
{ID: 413, English: "Plenty of sleep is healthful.", Chinese: "充足的睡眠有益於健康。"},
{ID: 414, English: "The sun comes up in the east.", Chinese: "太陽從東方升起。"},
{ID: 415, English: "This is because we feel pain.", Chinese: "這是因為我們能感到疼痛。"},
{ID: 416, English: "What do you desire me to do?", Chinese: "你想要我做什麼?"},
{ID: 417, English: "What you said was quite true.", Chinese: "你所說的完全符合事實。"},
{ID: 418, English: "You can either stay or leave.", Chinese: "你可以留下或者離開。"},
{ID: 419, English: "Your life is your own affair.", Chinese: "你的生活是你自己的事。"},
{ID: 420, English: "All that glitters is not gold.", Chinese: "金玉其外，未必皆善（不可僅以貌取人）。"},
{ID: 421, English: "Are you going to have a party?", Chinese: "你要舉行聚會嗎?"},
{ID: 422, English: "Aren't you concerned about it?", Chinese: "難道你不擔心嗎?"},
{ID: 423, English: "Don't forget to keep in touch.", Chinese: "別忘了保持聯繫。"},
{ID: 424, English: "He broke his words once again.", Chinese: "他又一次違背了諾言。"},
{ID: 425, English: "He is in his everyday clothes.", Chinese: "他穿著平常的衣服。"},
{ID: 426, English: "He is taller than I by a head.", Chinese: "他比我高一頭。"},
{ID: 427, English: "He led them down the mountain.", Chinese: "他帶他們下山。"},
{ID: 428, English: "He was trained to be a lawyer.", Chinese: "他被培養成一名律師。"},
{ID: 429, English: "I am afraid that l have to go.", Chinese: "我要走了。"},
{ID: 430, English: "I don't have any cash with me.", Chinese: "我身上沒帶現金。"},
{ID: 431, English: "I have been putting on weight.", Chinese: "我開始發胖了。"},
{ID: 432, English: "I have just finished the book.", Chinese: "我剛剛讀完這本書。"},
{ID: 433, English: "I was late for work yesterday.", Chinese: "我昨天上班遲到了。"},
{ID: 434, English: "It appears to be a true story.", Chinese: "這故事似乎是真的。"},
{ID: 435, English: "I've got to start working out.", Chinese: "我必須開始做健身運動了。"},
{ID: 436, English: "Japan is to the east of China.", Chinese: "日本在中國的東部。"},
{ID: 437, English: "John asked Grace to marry him.", Chinese: "約翰向格雷斯求婚。"},
{ID: 438, English: "My watch is faster than yours.", Chinese: "我的錶比你的錶快。"},
{ID: 439, English: "New China was founded in l949.", Chinese: "1949年新中國成立。"},
{ID: 440, English: "Thanks for your compliment.", Chinese: "多謝你的誇獎。"},
{ID: 441, English: "They charged the fault on him.", Chinese: "他們把過失歸咎於他。"},
{ID: 442, English: "This car is in good condition.", Chinese: "這車性能很好。"},
{ID: 443, English: "This work itself is very easy.", Chinese: "這件工作本身很容易。"},
{ID: 444, English: "Truth is the daughter of time.", Chinese: "時間見真理。"},
{ID: 445, English: "We look forward to your visit.", Chinese: "期待您的光臨。"},
{ID: 446, English: "What do you think of this one?", Chinese: "您覺得這個怎麼樣子"},
{ID: 447, English: "What's the weather like today?", Chinese: "今天天氣怎麼樣?"},
{ID: 448, English: "A red tie will match that suit.", Chinese: "紅領帶能搭配那件衣服。"},
{ID: 449, English: "A wet road is usually slippery.", Chinese: "潮濕的路往往是滑的。"},
{ID: 450, English: "Example is better than precept。", Chinese: "身教勝於言傳。"},
{ID: 451, English: "Go right back to the beginning.", Chinese: "直接回到起始位置。"},
{ID: 452, English: "He does everything without aim.", Chinese: "他做事都漫無目標。"},
{ID: 453, English: "He is respectful to his elders.", Chinese: "他對長輩很恭敬。"},
{ID: 454, English: "He knows English better than I.", Chinese: "他比我懂英語。"},
{ID: 455, English: "He resolved to give up smoking.", Chinese: "他決心戒煙。"},
{ID: 456, English: "His talk covered many subjects.", Chinese: "他的報告涉及很多課題。"},
{ID: 457, English: "I fear that he drinks too much.", Chinese: "我擔心他喝的酒太多了。"},
{ID: 458, English: "I have my hair cut every month.", Chinese: "我每個月都理髮。"},
{ID: 459, English: "I want to have a part-time job.", Chinese: "我想有一份兼職工作。"},
{ID: 460, English: "I'm sorry to have bothered you.", Chinese: "對不起，打擾你了。"},
{ID: 461, English: "It is not so easy as you think.", Chinese: "這事沒有你想像的那麼簡單。"},
{ID: 462, English: "Keep your temper under control.", Chinese: "不要發脾氣。 ."},
{ID: 463, English: "Lying and stealing are immoral.", Chinese: "說謊和偷竊都是不道德的。"},
{ID: 464, English: "My efforts resulted in nothing.", Chinese: "我的努力毫無結果。"},
{ID: 465, English: "My false teeth are stuck to it.", Chinese: "我的假牙還在上邊呢!"},
{ID: 466, English: "She is a composer for the harp.", Chinese: "她是位寫豎琴曲的作曲家"},
{ID: 467, English: "Take me to the airport, please.", Chinese: "請送我去機場。"},
{ID: 468, English: "Talking with you is a pleasure.", Chinese: "和你談話很愉快"},
{ID: 469, English: "The eggs are sold by the dozen.", Chinese: "雞蛋按打賣。"},
{ID: 470, English: "The price just covers the cost.", Chinese: "這個價格正好抵消成本。"},
{ID: 471, English: "The sweater is of good quality.", Chinese: "這件毛衣質地很好。"},
{ID: 472, English: "The teacher got a little angry.", Chinese: "老師有點生氣了。"},
{ID: 473, English: "Think carefully before you act.", Chinese: "三思而後行。"},
{ID: 474, English: "Walt invented the steam engine.", Chinese: "瓦特發明了蒸汽機。"},
{ID: 475, English: "We are divided in our opinions.", Chinese: "我們意見分歧。"},
{ID: 476, English: "What ever I said, he'd disagree.", Chinese: "不論我說什麼他都不同意。"},
{ID: 477, English: "Whoever comes will be welcomed.", Chinese: "來的人我們都歡迎。"},
{ID: 478, English: "You look as if you didn't care.", Chinese: "你看上去好像滿不在乎。"},
{ID: 479, English: "You should look at it yourself.", Chinese: "你應該親自看看它。"},
{ID: 480, English: "Draw your chair up to the table.", Chinese: "把你的椅子拉到桌子旁邊來。"},
{ID: 481, English: "He covered himself with a quilt.", Chinese: "他給自己蓋上一條被。"},
{ID: 482, English: "He found my lecture interesting.", Chinese: "他覺得我講課有趣。"},
{ID: 483, English: "He had a good many friends here.", Chinese: "他在這兒有很多朋友。"},
{ID: 484, English: "He is only about five feet high.", Chinese: "他大概只有五英尺高。"},
{ID: 485, English: "Her family are all music lovers.", Chinese: "她全家人都是音樂愛好者。"},
{ID: 486, English: "I am busy. How is your business?", Chinese: "我很忙。你的生意做得怎樣?"},
{ID: 487, English: "I don't think much of the movie.", Chinese: "我認為那電影不怎麼樣。"},
{ID: 488, English: "I feel like eating an ice-cream.", Chinese: "我想吃一個冰淇淋。"},
{ID: 489, English: "I found him seated on the bench.", Chinese: "我發現他在椅子上坐著"},
{ID: 490, English: "I gave much time to the old car.", Chinese: "我在這輛破車上花了不少時間。"},
{ID: 491, English: "I lost the door key about here.", Chinese: "我在這附近掉了門鑰匙。"},
{ID: 492, English: "I'm not guessing, I really know.", Chinese: "我不是在猜想,我真的知道。"},
{ID: 493, English: "It's time to tell her the truth.", Chinese: "是該告訴她真相的時候了。"},
{ID: 494, English: "Let's watch TV with a candle on.", Chinese: "咱們點上蠟燭看電視吧。"},
{ID: 495, English: "Most games cost about that much.", Chinese: "大部分遊戲差不多都是這個價錢。"},
{ID: 496, English: "My parents want me to go abroad.", Chinese: "我父母想讓我出國。"},
{ID: 497, English: "She has been collecting stamps.", Chinese: "她一直收集郵票。"},
{ID: 498, English: "There are many stars in the sky.", Chinese: "天上有很多星星。"},
{ID: 499, English: "We get to London this afternoon.", Chinese: "我們是今天下午到達倫敦的。"},
{ID: 500, English: "What about having a pizza first?", Chinese: "先吃點批薩怎麼樣?"},
{ID: 501, English: "You'd better look before you leap.", Chinese: "你最好三思而後行。"},
{ID: 502, English: "You know what I'm talking about.", Chinese: "我想你知道我在說什麼。"},
{ID: 503, English: "He has been sick for three weeks.", Chinese: "他已經病了幾周了。"},
{ID: 504, English: "He inspected the car for defects.", Chinese: "他詳細檢查車子有無故障。"},
{ID: 505, English: "I count you as one of my friends.", Chinese: "我把你算作我的一個朋友。"},
{ID: 506, English: "I go to school by bike every day.", Chinese: "我每天騎自行車上學。"},
{ID: 507, English: "I have a large collection of CDs.", Chinese: "我收集了很多唱片。"},
{ID: 508, English: "I won't be able to see him today.", Chinese: "今天我不可能去看他。"},
{ID: 509, English: "I'll call a taxi in case of need.", Chinese: "如果需要,我會叫計程車的。"},
{ID: 510, English: "Is there any sugar in the bottle?", Chinese: "瓶子裏還有糖嗎?"},
{ID: 511, English: "It's a secret between you and me.", Chinese: "這是你我之間的秘密。"},
{ID: 512, English: "It's very kind of you to help me.", Chinese: "你幫助我真是太好了。"},
{ID: 513, English: "Let's divide the cake into three.", Chinese: "我們將蛋糕分成三份吧。"},
{ID: 514, English: "Patience is a mark of confidence.", Chinese: "耐心是自信心的一種表現。"},
{ID: 515, English: "Susan is going to finish college.", Chinese: "蘇珊將完成大學學業。"},
{ID: 516, English: "That is my idea about friendship.", Chinese: "這是我關於友誼的看法。"},
{ID: 517, English: "The book you ask for is sold out.", Chinese: "你要的那本書已經售完了。"},
{ID: 518, English: "The boy was too nervous to speak.", Chinese: "那男孩緊張得說不出話來。"},
{ID: 519, English: "The play may begin at any moment.", Chinese: "戲隨時都有可能開始。"},
{ID: 520, English: "The salve will heal slight burns.", Chinese: "這種藥膏能治療輕微燒傷。"},
{ID: 521, English: "The sea sparkled in the sunlight.", Chinese: "陽光下,大海波光粼粼。"},
{ID: 522, English: "The teacher tested us in English.", Chinese: "老師用英文考我們。"},
{ID: 523, English: "There is a bridge over the river.", Chinese: "河上有一座橋。"},
{ID: 524, English: "They rode their respective bikes.", Chinese: "他們各自騎著自己的自行車。"},
{ID: 525, English: "They will arrive in half an hour.", Chinese: "他們將於半小時之內到達。"},
{ID: 526, English: "Time is more valuable than money.", Chinese: "時間比金錢寶貴。"},
{ID: 527, English: "We are all in favor of this plan.", Chinese: "我們都贊同這項計劃。"},
{ID: 528, English: "We reached London this afternoon.", Chinese: "我們是今天下午到達倫敦的。"},
{ID: 529, English: "We two finished a bottle of wine.", Chinese: "我倆喝完了一瓶酒。"},
{ID: 530, English: "What a lovely little girl she is!", Chinese: "她是一個多麼可愛的小女孩耶!"},
{ID: 531, English: "Will you pick me up at my place?", Chinese: "你能到我的住處來接我嗎?"},
{ID: 532, English: "You may choose whatever you like", Chinese: "喜歡什麼就選什麼。"},
{ID: 533, English: "You're suffering from an allergy?", Chinese: "你過敏嗎?"},
{ID: 534, English: "Beyond all questions you are right.", Chinese: "毫無疑問,你是對的。"},
{ID: 535, English: "But I plan to weed the yard today.", Chinese: "我計劃今天除院子裏的草。"},
{ID: 536, English: "But who will do all the housework?", Chinese: "但是這些家務活誰來做呢?"},
{ID: 537, English: "Close the door after you, please.", Chinese: "請隨手關門。"},
{ID: 538, English: "Come to see me whenever you like。", Chinese: "你可以隨時來見我。"},
{ID: 539, English: "Don't pull the chairs about, boys!", Chinese: "不要把椅子拖來拖去，孩子們!"},
{ID: 540, English: "He drives more carefully than you.", Chinese: "他開車比你小心。"},
{ID: 541, English: "He invited me to dinner yesterday.", Chinese: "他昨天請我吃晚飯了。"},
{ID: 542, English: "He struck his attacker on the ear.", Chinese: "他打了那個攻擊者一耳光。"},
{ID: 543, English: "He suddenly appeared in the party.", Chinese: "他突然在晚會上出現了。"},
{ID: 544, English: "Her handbag goes with her clothes.", Chinese: "她的手袋和她的衣服很搭配。"},
{ID: 545, English: "Here we are. Row M, seats l and 3.", Chinese: "哦,到了。M排，l號和3號。"},
{ID: 546, English: "His boss might get angry with him.", Chinese: "他的老闆也許會生他的氣。"},
{ID: 547, English: "I expect to be there this evening.", Chinese: "我打算今天晚上到那兒去。"},
{ID: 548, English: "I really need to lose some weight.", Chinese: "我真的需要減肥了。"},
{ID: 549, English: "I think you have the wrong number.", Chinese: "我想你打錯號碼了。"},
{ID: 550, English: "I would rather stay at home alone.", Chinese: "我寧願獨自呆在家。"},
{ID: 551, English: "I'd like to look at some sweaters.", Chinese: "我想看看毛衣。"},
{ID: 552, English: "Its origin is still a mystery now.", Chinese: "它的起源至今仍是個謎。"},
{ID: 553, English: "Money is no more than our servant.", Chinese: "金錢不過是我們的僕人。"},
{ID: 554, English: "Once you begin, you must continue", Chinese: "一旦開始，你就得繼續。"},
{ID: 555, English: "She is poor but quite respectable.", Chinese: "她雖窮，人品卻很端正。"},
{ID: 556, English: "She spent a lot of money on books.", Chinese: "她花了很多錢來買書。"},
{ID: 557, English: "The girl in red is his girlfriend.", Chinese: "穿紅衣服的那個女孩是他的女朋友。"},
{ID: 558, English: "There is a chair below the window.", Chinese: "窗戶下面有一把椅子。"},
{ID: 559, English: "They employed him as a consultant.", Chinese: "他們雇用他為顧問。"},
{ID: 560, English: "To be honest with you, I'm twenty.", Chinese: "老實說,我20歲。"},
{ID: 561, English: "We often call him by his nickname.", Chinese: "我們經常叫他的綽號。"},
{ID: 562, English: "Will you be free tomorrow evening?", Chinese: "你明晚有空嗎?"},
{ID: 563, English: "Would you like to leave a message?", Chinese: "你要留話嗎?"},
{ID: 564, English: "You can never turn the clock back.", Chinese: "時光不能倒流。"},
{ID: 565, English: "You may as well tell me the truth.", Chinese: "你還是把事實告訴我為好。"},
{ID: 566, English: "Are your grandparents still living?", Chinese: "你的祖父母還在麼?"},
{ID: 567, English: "Can you recognize that woman, Mary?", Chinese: "你能認出那個女人是誰了嗎，瑪麗?"},
{ID: 568, English: "Do you have any suggestions for me?", Chinese: "你對我有什麼建議麼?"},
{ID: 569, English: "He is tough, but I am even tougher.", Chinese: "他是一個硬漢子，不過我要比他更硬。"},
{ID: 570, English: "He made his way through the forest.", Chinese: "他設法穿過了森林。"},
{ID: 571, English: "He suggests you leave here at once.", Chinese: "他建議你立刻離開這兒。"},
{ID: 572, English: "He was married to a friend of mine.", Chinese: "他和我的一個朋友結了婚。"},
{ID: 573, English: "He will blame you for carelessness.", Chinese: "他會責備你的粗心大意。"},
{ID: 574, English: "I can give you a number of excuses.", Chinese: "我可以給你說出很多韻理由。"},
{ID: 575, English: "I don't doubt that he will help me.", Chinese: "我不懷疑他會援助我。"},
{ID: 576, English: "I hope you enjoy your stay with us.", Chinese: "希望您在這兒過的愉快。"},
{ID: 577, English: "I'd like to repair our differences.", Chinese: "我願意消除一下我們之間的分歧。"},
{ID: 578, English: "It's nothing to be surprised about.", Chinese: "這事不值得大驚小怪。"},
{ID: 579, English: "It's rude to stare at other people.", Chinese: "盯著別人看是不禮貌的。"},
{ID: 580, English: "Bob has always had a crush on Lucy.", Chinese: "鮑伯一直在愛著露茜。"},
{ID: 581, English: "Let's take a short break for lunch.", Chinese: "讓我們休息一會兒,去吃午飯。"},
{ID: 582, English: "Linda speaks as if she were a boss.", Chinese: "琳達說話總好像她是老闆。"},
{ID: 583, English: "She became more and more beautiful.", Chinese: "她變得越來越漂亮了。"},
{ID: 584, English: "Suppose it rains, what shall we do?", Chinese: "萬一下雨,我們該怎麼辦?"},
{ID: 585, English: "The book is protected by copyright.", Chinese: "該書受版權保護。"},
{ID: 586, English: "The ice is hard enough to skate on.", Chinese: "冰已經厚得可以溜冰了。"},
{ID: 587, English: "The price includes postage charges.", Chinese: "價格包括郵資在內。"},
{ID: 588, English: "This is a little something for you.", Chinese: "這是我給你們的一點心意。"},
{ID: 589, English: "What he likes best is making jokes.", Chinese: "他最喜歡開玩笑。"},
{ID: 590, English: "Who but Jack would do such a thing?", Chinese: "除了傑克，誰會做這種事呢?"},
{ID: 591, English: "You should have a mind of your own.", Chinese: "你必須有自己的主見。"},
{ID: 592, English: "You will soon get used to the work.", Chinese: "你很快就會習慣於這項工作的。"},
{ID: 593, English: "Columbus discovered America in 1492.", Chinese: "哥倫布於1492年發現了美洲。"},
{ID: 594, English: "God helps those who help themselves.", Chinese: "天助自助者。"},
{ID: 595, English: "He has a nice sum of money put away.", Chinese: "他存了一大筆錢。"},
{ID: 596, English: "He is heavily insured against death.", Chinese: "他給自己投了鉅額的人身保險。"},
{ID: 597, English: "He used to learn everything by rote.", Chinese: "他過去總是死記硬背。"},
{ID: 598, English: "He's a terrible man when he's angry.", Chinese: "他生氣的時候很可怕。"},
{ID: 599, English: "I am on my way to the grocery store.", Chinese: "我正在去雜貨店的路上。"},
{ID: 600, English: "I am sick of always waiting for you!", Chinese: "你，老讓我等你，真是煩透了。"},
{ID: 601, English: "I appreciate John's helping in time.", Chinese: "我感謝約翰的及時幫助。"},
{ID: 602, English: "I bought it the day it was released.", Chinese: "它發行的當天我就買了。"},
{ID: 603, English: "I doubted whether the story is true.", Chinese: "我懷疑那故事是不是真的。"},
{ID: 604, English: "I learnt that I had passed the test.", Chinese: "我獲悉我測驗及格了。"},
{ID: 605, English: "I will seek from my doctor's advice.", Chinese: "我將請教醫生的意見。"},
{ID: 606, English: "Ice cream is popular among children.", Chinese: "冰淇淋深受孩子們的歡迎。"},
{ID: 607, English: "I'd like to get this film developed.", Chinese: "我要沖洗這卷膠捲。"},
{ID: 608, English: "In a word, I am tired of everything.", Chinese: "總之,我對一切都很厭倦。"},
{ID: 609, English: "Let us do it by ourselves, will you?", Chinese: "我們自己做這件事,可以嗎?"},
{ID: 610, English: "May I know the quantity you require?", Chinese: "請問你們需要多少數量的貨物?"},
{ID: 611, English: "Nobody has ever solved this problem.", Chinese: "沒有人曾解決過這個問題。"},
{ID: 612, English: "Our school covers 100 square meters.", Chinese: "我們學校佔地面積平方米。"},
{ID: 613, English: "People enjoyed the stamps very much.", Chinese: "人們非常喜愛這些郵票。"},
{ID: 614, English: "The editor overlooked a print error.", Chinese: "這位編輯漏掉了一個印刷錯誤。"},
{ID: 615, English: "The sudden barking frightened Clara.", Chinese: "突然的狗叫聲嚇壞了克拉拉。"},
{ID: 616, English: "The teams are coming onto the field.", Chinese: "隊員們都進場了。"},
{ID: 617, English: "There is a mark of ink on his shirt.", Chinese: "他的襯衣上有一塊墨跡。"},
{ID: 618, English: "There isn't any water in the bottle.", Chinese: "瓶子裏一點水也沒有。"},
{ID: 619, English: "This joke has gone a little too far.", Chinese: "這個玩笑開得有點過分了。"},
{ID: 620, English: "We arrived in London this afternoon。", Chinese: "我們是今天下午到達倫敦的。"},
{ID: 621, English: "We can't go out because of the rain.", Chinese: "我們不能出去因為下雨了。"},
{ID: 622, English: "We should make good use of our time.", Chinese: "我們應該充分利用我們的時間。"},
{ID: 623, English: "We should save unnecessary expenses.", Chinese: "我們應節省不必要的開支。"},
{ID: 624, English: "You may have heard of Birth Control.", Chinese: "你們也許聽說過控制人口出生的措施。"},
{ID: 625, English: "After a pause he continued his story.", Chinese: "停頓一下之後他繼續說他的。"},
{ID: 626, English: "As you know, I am a very kind person.", Chinese: "你知道,我是個很和善的人。"},
{ID: 627, English: "He dare not tell us his evil conduct.", Chinese: "他不敢告訴我們他的惡行。"},
{ID: 628, English: "I can express myself in good English.", Chinese: "我可以用很好的英語來表達自己的觀點。"},
{ID: 629, English: "I'll furnish my house with furniture.", Chinese: "我要為我的房子置辦傢具。"},
{ID: 630, English: "It seemed as if there was no way out.", Chinese: "看情形似乎沒有出路了。"},
{ID: 631, English: "It's the hottest day I've had so far.", Chinese: "這是迄今為止我經歷的最熱的一天。"},
{ID: 632, English: "Mr.Smith is in charge of this class.", Chinese: "史密斯老師負責該班。"},
{ID: 633, English: "Mr. Smith taught English at a school.", Chinese: "史密斯先生在一所學校教英語。"},
{ID: 634, English: "None of us is afraid of difficulties.", Chinese: "我們當中沒有一個人害怕困難。"},
{ID: 635, English: "Our school is in the east of Taipei.", Chinese: "我們學校在台北的東邊。"},
{ID: 636, English: "She really wishes her clock had rung.", Chinese: "她真希望今早她的鬧鐘響了。"},
{ID: 637, English: "She teaches foreign students Chinese.", Chinese: "她教外國學生華(漢)語。"},
{ID: 638, English: "The question will be settled tonight.", Chinese: "這個問題將在今晚解決。"},
{ID: 639, English: "The weight is too much for my height.", Chinese: "相對於我的身高來說，體重太重了!"},
{ID: 640, English: "There are mice in Mrs. Lee's kitchen!", Chinese: "李太太的廚房裏有老鼠!"},
{ID: 641, English: "There is no one but hopes to be rich.", Chinese: "沒有人不想發財。"},
{ID: 642, English: "There'll be some sport reviews on TV.", Chinese: "電視上會有一些體育評論。"},
{ID: 643, English: "This company is our regular customer.", Chinese: "這家公司是我們的老客戶。"},
{ID: 644, English: "This is a good example of his poetry.", Chinese: "這是他詩作的一個好例子。"},
{ID: 645, English: "What we read influences our thinking.", Chinese: "我們所閱讀的書本會影響我們的思想。"},
{ID: 646, English: "Words can't express what I felt then.", Chinese: "無法用語言形容我當時的感受。"},
{ID: 647, English: "You really have an ear for pop music.", Chinese: "你確實對流行音樂很有欣賞力。"},
{ID: 648, English: "A bad workman quarrels with his tools.", Chinese: "手藝差的工人總是抱怨工具不好使。"},
{ID: 649, English: "Can you adapt yourself to the new job?", Chinese: "你能適應新的工作嗎?"},
{ID: 650, English: "Does the computer ever make a mistake?", Chinese: "電腦出錯嗎?"},
{ID: 651, English: "Don't be uneasy about the consequence", Chinese: "不必為後果憂慮不安。"},
{ID: 652, English: "Even a child can answer this question", Chinese: "即使小孩都能回答問題。"},
{ID: 653, English: "He has many strange ideas in his mind.", Chinese: "他腦內盡是奇思怪想。"},
{ID: 654, English: "He is commonly supposed to be foolish.", Chinese: "他是公認的傻瓜。"},
{ID: 655, English: "He sat with his arms across the chest.", Chinese: "他雙臂交叉於胸前坐著。"},
{ID: 656, English: "He set up a fine example to all of us.", Chinese: "他為我們樹立了一個好榜樣。"},
{ID: 657, English: "His cake is four times as big as mine.", Chinese: "他的蛋糕是我的四倍大。"},
{ID: 658, English: "I do not care whether it rains or not.", Chinese: "我不管天會不會下雨。"},
{ID: 659, English: "I have a lot in common with my sister.", Chinese: "我和我姐姐有很多相同之處。"},
{ID: 660, English: "I haven't even touched your tooth yet.", Chinese: "我還沒有碰到你的牙齒呢。"},
{ID: 661, English: "I'm looking forward to a prompt reply.", Chinese: "盼迅速答覆。"},
{ID: 662, English: "It is an excellent novel in every way.", Chinese: "無論從哪方面來看,這都是一本優秀的小說。"},
{ID: 663, English: "It is clear that the cat has eaten it!", Chinese: "很明顯，是貓偷吃的!"},
{ID: 664, English: "Nothing but death can part the couple.", Chinese: "除了死之外,什麼也拆不散這一對。"},
{ID: 665, English: "Now she looks pale as if she were ill.", Chinese: "現在她臉色難看,好像病了一樣。"},
{ID: 666, English: "She was injured badly in the accident.", Chinese: "她在這次意外中受到重傷。"},
{ID: 667, English: "The secret was spread among the crowd.", Chinese: "秘密在人群當中傳播開來。"},
{ID: 668, English: "The two brothers look very much alike.", Chinese: "這兄弟倆看上去很相像。"},
{ID: 669, English: "Their interest is listening to others.", Chinese: "他們的興趣是聽別人說話。"},
{ID: 670, English: "There was a notice in the supermarket.", Chinese: "超市裏有一個佈告。"},
{ID: 671, English: "This one cannot compare with that one.", Chinese: "這個與那個無法比較。"},
{ID: 672, English: "To know everything is to know nothing.", Chinese: "樣樣通，樣樣不精。"},
{ID: 673, English: "To tell the truth, I don't like disco.", Chinese: "說實話，我不喜歡迪斯可。"},
{ID: 674, English: "True and False have opposite meanings.", Chinese: "真與假含義完全相反。"},
{ID: 675, English: "What's the point of going to college?", Chinese: "上大學有何用?"},
{ID: 676, English: "Where can we make the insurance claim?", Chinese: "我們可以在哪提出保險賠償?"},
{ID: 677, English: "Why don't I pick you up at your house?", Chinese: "為什麼不讓我去接你呢?"},
{ID: 678, English: "Why don't you attend an aerobic class?", Chinese: "你為什麼不去參加一個有氧健身班呢?"},
{ID: 679, English: "You can kill two birds with one stone.", Chinese: "一舉兩得。"},
{ID: 680, English: "You can't go in no matter who you are.", Chinese: "不管你是誰,都不能進去。"},
{ID: 681, English: "You should learn these words by heart.", Chinese: "你應該把這些詞背熟。"},
{ID: 682, English: "Could I have those two tickets, please?", Chinese: "兩張票給我行不行?"},
{ID: 683, English: "He has to take care of his sick mother.", Chinese: "他得照顧他生病的母親。"},
{ID: 684, English: "He hired a workman to repair the fence.", Chinese: "他雇用了一個工人修理圍墻。"},
{ID: 685, English: "I can't make this machine run properly.", Chinese: "我無法使這部機器正常運轉。"},
{ID: 686, English: "I don't know if I'll have the patience.", Chinese: "我不知道我有沒有耐心。"},
{ID: 687, English: "I don't like what you are saying.", Chinese: "我不喜歡你說的話。"},
{ID: 688, English: "I fell in love with her at first sight.", Chinese: "我第一眼見到她就愛上了她。"},
{ID: 689, English: "I have just heard from my sister, Mary.", Chinese: "我剛收到我妹妹瑪麗的一封信。"},
{ID: 690, English: "If you would only try, you could do it.", Chinese: "只要你肯嘗試,你一定能做這件事。"},
{ID: 691, English: "It is no use learning without thinking.", Chinese: "學而不思則惘。"},
{ID: 692, English: "It was a lazy, breezy autumn afternoon.", Chinese: "這是一個懶散的，起風的秋日下午。"},
{ID: 693, English: "Jack is the strongest boy in the class.", Chinese: "傑克是全班最強壯的男孩。"},
{ID: 694, English: "Please fetch a chair from another room.", Chinese: "請到別的房間取一把椅子。"},
{ID: 695, English: "The doctor began to operate on the boy.", Chinese: "醫生開始給那個男孩動手術。"},
{ID: 696, English: "The doctor is taking my blood pressure.", Chinese: "醫生正給我量血壓。"},
{ID: 697, English: "The machines will not operate properly.", Chinese: "那些機器不能正常運轉。"},
{ID: 698, English: "The students declared against cheating.", Chinese: "學生們表示反對作弊。"},
{ID: 699, English: "There is hope as long as he is with us.", Chinese: "只要他在，就有希望。"},
{ID: 700, English: "He talks as if he were the head of the office.", Chinese: "他說話的口氣像辦公室主任似的。"},
{ID: 701, English: "His cake is three times bigger than mine.", Chinese: "他的蛋糕比我的大三倍。"},
{ID: 702, English: "I am looking forward to your early reply.", Chinese: "希望早日得到你的答覆。"},
{ID: 703, English: "I could say nothing but that I was sorry", Chinese: "我除了說“對不起”外，什麼也說不出來。"},
{ID: 704, English: "I don't know how to express my gratitude.", Chinese: "我不知道怎樣來表達我的感激之情。"},
{ID: 705, English: "I have to catch a plane. Could you hurry?", Chinese: "你能快點嗎? 我要趕搭飛機。"},
{ID: 706, English: "I haven't heard from her for a long time.", Chinese: "我好久沒有她的消息了。"},
{ID: 707, English: "I would like to wash the clothes for you.", Chinese: "我願意幫你洗這些衣服。"},
{ID: 708, English: "Let me see your driver's license, please.", Chinese: "請讓我看看你的駕駛執照。"},
{ID: 709, English: "She goes to work every day except Sunday.", Chinese: "除星期天外,他每天去上班。"},
{ID: 710, English: "Take a seat please, make yourself at home.", Chinese: "請坐，隨便一點。"},
{ID: 711, English: "The damage was caused by external forces.", Chinese: "損害是由外力引起的。"},
{ID: 712, English: "The doctor advised me to give up smoking.", Chinese: "醫生建議我戒煙。"},
{ID: 713, English: "The flowers make the room more beautiful.", Chinese: "花朵使房間變得更加美了。"},
{ID: 714, English: "There is a good restaurant on the street.", Chinese: "那條大街上有一個很好的餐館。"},
{ID: 715, English: "They covered 120 miles in a single night.", Chinese: "他們僅一夜就走了120英里路。"},
{ID: 716, English: "Try to look on the bright side of things.", Chinese: "儘量從好的方面看。"},
{ID: 717, English: "What's your plan for the summer vacation?", Chinese: "你暑假打算幹什麼?"},
{ID: 718, English: "You may pick whichever one you like best.", Chinese: "你可以挑你最喜歡的。"},
{ID: 719, English: "You're welcome to stay with us next time.", Chinese: "歡迎您下次再光臨我們的飯店。"},
{ID: 720, English: "There was a murder in London yesterday.", Chinese: "昨天倫敦發生了一起謀殺案。"},
{ID: 721, English: "They stared at the huge tiger with awe.", Chinese: "他們敬畏地看著那頭巨虎。"},
{ID: 722, English: "He never misses a chance to see a movie.", Chinese: "他從不錯過看電影的機會。"},
{ID: 723, English: "I cannot put up with my noisy roommates.", Chinese: "我受不了我那些吵鬧的室友了。"},
{ID: 724, English: "I will be back by the end of next month.", Chinese: "我下個月底會回來。"},
{ID: 725, English: "I'm good at freestyle and breast stroke.", Chinese: "我擅長自由式和蛙泳。"},
{ID: 726, English: "It was your turn to wash them yesterday.", Chinese: "昨天輪到你把它們洗乾淨。"},
{ID: 727, English: "Let's go out to have a dinner, shall we?", Chinese: "咱們出去吃飯吧,好嗎?"},
{ID: 728, English: "Please push the ladder against the wall.", Chinese: "請把梯子靠在牆壁上。"},
{ID: 729, English: "She is standing in the front of the bus.", Chinese: "她站在公共汽車的前面。"},
{ID: 730, English: "The doctor asked me to watch what I eat.", Chinese: "醫生要我注意飲食。"},
{ID: 731, English: "The grass is moist early in the morning.", Chinese: "清晨的草地濕漉漉的。"},
{ID: 732, English: "The test finished. We began our holiday.", Chinese: "考試結束了,我們開始放假。"},
{ID: 733, English: "This question is too complicated for me.", Chinese: "這個問題對我說來太複雜了。"},
{ID: 734, English: "Tony speaks English and he plays tennis.", Chinese: "東尼會說英語，打網球。"},
{ID: 735, English: "What is worth doing is worth doing well.", Chinese: "只要覺得某事值得做，就要把它做好。"},
{ID: 736, English: "Would you like to go to a party with me?", Chinese: "你想不想和我一起去參加一個聚會?"},
{ID: 737, English: "All at once, a rabbit came out of a hole.", Chinese: "突然,一隻兔子從一個洞中跑了出來。"},
{ID: 738, English: "All characters in the book are imaginary.", Chinese: "書中所有的人物都是虛構的。"},
{ID: 739, English: "Do you feel like going to that new disco?", Chinese: "你想去那個新開的迪斯可廳？"},
{ID: 740, English: "Ducks know how to swim when they are born.", Chinese: "鴨子天生會游泳。"},
{ID: 741, English: "He spent most of his life gathering money.", Chinese: "他一生大部分時間用來積聚錢財。"},
{ID: 742, English: "He usually stays at home with his pet dog.", Chinese: "他通常跟他的愛犬待在家裏。"},
{ID: 743, English: "How peaceful and beautiful the country is!", Chinese: "鄉下多麼平靜美麗！"},
{ID: 744, English: "I am told that you dance wonderfully well.", Chinese: "我聽說你的舞跳得特棒。"},
{ID: 745, English: "I have had several conversations with him.", Chinese: "我已經和他談過幾次了。"},
{ID: 746, English: "It is the best film that I have ever seen.", Chinese: "這是我所看過的最好的電影。"},
{ID: 747, English: "It's only a party in honor of my birthday.", Chinese: "這只是為了慶祝我的生日而舉行的晚會。"},
{ID: 748, English: "Learning English is like building a house.", Chinese: "學英語像蓋房子。"},
{ID: 749, English: "Listening with your heart is good for you.", Chinese: "專心聆聽別人說話對你有好處。"},
{ID: 750, English: "My grandpa died of hunger in the old days.", Chinese: "我爺爺在舊社會死於饑餓。"},
{ID: 751, English: "She feared staying alone in the farmhouse.", Chinese: "她害怕一個人留在農舍裏。"},
{ID: 752, English: "She guided the tourists around the castle.", Chinese: "她引導旅遊者參觀了這座城堡。"},
{ID: 753, English: "She runs everyday in order to lose weight.", Chinese: "她每天都跑步是為了減肥。"},
{ID: 754, English: "She sang perfectly in the hall last night.", Chinese: "她昨晚在大廳唱得非常好。"},
{ID: 755, English: "Somebody is always complaining to others.", Chinese: "有人總是向別人抱怨。"},
{ID: 756, English: "They don't often have a bad day this year.", Chinese: "他們今年的運氣還不錯。"},
{ID: 757, English: "We regard the matter as nothing important.", Chinese: "我們認為這件事情不重要。"},
{ID: 758, English: "We'll take our holiday sometime in August.", Chinese: "我們將在八月份的某個時候休假。"},
{ID: 759, English: "Could you direct me to the station, please?", Chinese: "請問到車站怎麼走?"},
{ID: 760, English: "Have you cleared your luggage with customs?", Chinese: "你的行李通關了嗎?"},
{ID: 761, English: "He bothered me with a great many questions.", Chinese: "他對我提了一大堆問題，真煩!"},
{ID: 762, English: "He does exercises every day in the morning.", Chinese: "他每天早上鍛練身體。"},
{ID: 763, English: "How do I control myself? I can't calm down.", Chinese: "我怎能控制我自己?我無法冷靜下來。"},
{ID: 764, English: "I dig songs and I like pop music very much.", Chinese: "我特別喜歡歌曲和流行音樂。"},
{ID: 765, English: "I'd like to cash a traveler's check please.", Chinese: "我想兌換旅行支票。"},
{ID: 766, English: "I'd like to pick sea shells this afternoon.", Chinese: "今天下午我想去撿貝殼。"},
{ID: 767, English: "It's odd that they didn't reply our letter.", Chinese: "他們沒有給我們回信,這真奇怪。"},
{ID: 768, English: "John seldom gets together with his friends.", Chinese: "約翰很少與朋友聚在一起。"},
{ID: 769, English: "Many people have been out of work recently.", Chinese: "最近有許多人失業。"},
{ID: 770, English: "Please give my best regards to your family.", Chinese: "請代我向你們全家致以最誠摯的問候。"},
{ID: 771, English: "Some people have compared books to friends.", Chinese: "有些人把書比作朋友。"},
{ID: 772, English: "The bat together with the balls was stolen.", Chinese: "球拍和球全被偷了。"},
{ID: 773, English: "The color of her dress suits her very well.", Chinese: "她衣服的顏色很適合她。"},
{ID: 774, English: "The days get longer and the nights get shorter.", Chinese: "白天變長了，黑夜變短了。"},
{ID: 775, English: "The dress doesn't fit her. She is too thin.", Chinese: "這件衣服不適合她，她太瘦了。"},
{ID: 776, English: "The examination put a lot of stress on him.", Chinese: "那次考試給了他很大的壓力。"},
{ID: 777, English: "The mother sat the child at a little table.", Chinese: "母親安排孩子坐到小桌旁。"},
{ID: 778, English: "There is some difference between the twins.", Chinese: "這對雙胞胎有點兒不一樣。"},
{ID: 779, English: "They insisted on staying rather than going.", Chinese: "他們堅持留下來，而不願意走"},
{ID: 780, English: "Trust me, the game is really worth playing.", Chinese: "相信我,這遊戲確實值得一玩。"},
{ID: 781, English: "Unlike her friends, she never gave up hope.", Chinese: "與她的朋友的不同之處是,她從不放棄希望。"},
{ID: 782, English: "Well done! You are always doing a good job!", Chinese: "幹得不錯! 你總是幹得很出色!"},
{ID: 783, English: "We're planning a tour to Italy this summer.", Chinese: "我們計劃今年夏天到義大利去旅行。"},
{ID: 784, English: "Were there any letters for me this morning?", Chinese: "今天早上有我的信嗎?"},
{ID: 785, English: "Why isn't Mrs.Lee's cat catching the mice?", Chinese: "李太太的貓為何不在抓這些老鼠呢?"},
{ID: 786, English: "Your English is improving little by little.", Chinese: "你的英語正在漸漸提高。"},
{ID: 787, English: "Could you tell me where I can wash my hands?", Chinese: "請問洗手間怎麼走?"},
{ID: 788, English: "Do you have any plans for the long weekend?", Chinese: "你有辦法打發這個漫長的週末嗎?"},
{ID: 789, English: "He decided to bring a suit against his boss.", Chinese: "他決定起訴他的老闆。"},
{ID: 790, English: "He devoted his life to the study of science.", Chinese: "他把畢生獻給科學研究。"},
{ID: 791, English: "He had to choose between death and dishonor.", Chinese: "他不得不在死亡和恥辱之間選擇。"},
{ID: 792, English: "His previous attempts had been unsuccessful.", Chinese: "他以前的嘗試沒有成功。"},
{ID: 793, English: "I determined that nothing should be changed.", Chinese: "我決定什麼都不改變。"},
{ID: 794, English: "I don't think it will lead to a good result.", Chinese: "我認為這事不會有什麼好結果。"},
{ID: 795, English: "I have 4 books and 2 magazines to check out.", Chinese: "我有4本書和2本雜誌要借。"},
{ID: 796, English: "I think I've filled in everything correctly.", Chinese: "我想各項都填對了。"},
{ID: 797, English: "I'm not sure whether I have locked the door.", Chinese: "我沒把握是否鎖了門。"},
{ID: 798, English: "It took him a little time to fix that watch.", Chinese: "他很快就把錶修理好了。"},
{ID: 799, English: "My father is at home looking for the ticket.", Chinese: "我爸爸正在家裏找票呢!"},
{ID: 800, English: "Not until last week did I get a work permit.", Chinese: "直到上周我才拿到工作許可證。"},
{ID: 801, English: "She intends to make teaching her profession.", Chinese: "她想以教書為職業。"},
{ID: 802, English: "The letter \"x\" stands for an unknown number.", Chinese: "字母x代表未知數。"},
{ID: 803, English: "The sight of the dead body scared him stiff.", Chinese: "看到屍體把他嚇僵了。"},
{ID: 804, English: "There are lots of huge buildings in Beijing.", Chinese: "在北京有許多高大的建築物。"},
{ID: 805, English: "There is an interesting film on Channel one.", Chinese: "在一頻道有一部有趣的電影。"},
{ID: 806, English: "They plan to immigrate to Finland next year.", Chinese: "他們計劃明年移居芬蘭。"},
{ID: 807, English: "We enjoyed driving along the new expressway.", Chinese: "我們喜歡沿著新建的高速公路開車。"},
{ID: 808, English: "We need to cooperate perfectly to win the game.", Chinese: "要想贏得比賽，我們需要密切配合。"},
{ID: 809, English: "We need more than listening. We need action!", Chinese: "我們需要的不光是聽得進意見，我們要的是行動。"},
{ID: 810, English: "Yes. I wouldn't go home early if I were you.", Chinese: "是的，如果我是你，我不會早回家。"},
{ID: 811, English: "Your answer is satisfying. I feel satisfied.", Chinese: "你的答案是令人滿意的。我感到很滿意。"},
{ID: 812, English: "Betty and Susan are talking on the telephone.", Chinese: "貝蒂和蘇珊正在通電話。"},
{ID: 813, English: "Great efforts ensure the success of our work.", Chinese: "巨大的努力確保了我們工作的成功。"},
{ID: 814, English: "He has tasted the sweets and bitters of life.", Chinese: "他已嘗遍了人生的甜酸苦辣。"},
{ID: 815, English: "He said he was educated in the United States.", Chinese: "他說他是在美國受的教育。"},
{ID: 816, English: "How do you like our English literature professor?", Chinese: "你覺得我們的英國文學課的教授怎麼樣?"},
{ID: 817, English: "I am looking forward to your visit next week.", Chinese: "我期待著你下周來訪。"},
{ID: 818, English: "I feel I am the happiest person in the world.", Chinese: "我覺得自己是世界上最幸福的人了。"},
{ID: 819, English: "I had to sit up all night writing the report.", Chinese: "我不得不熬通宵寫報告。"},
{ID: 820, English: "I hope we can see each other again some time.", Chinese: "希望還能有相見的機會。"},
{ID: 821, English: "I saw him playing football on the playground.", Chinese: "我看見他在操場上踢足球。"},
{ID: 822, English: "It is tomorrow that they will have a meeting.", Chinese: "就在明天(而不是在別的某一天)他們要開會。"},
{ID: 823, English: "Let me tell you some details about clearance.", Chinese: "讓我告訴你一些通關的細節。"},
{ID: 824, English: "The brain needs a continuous supply of blood.", Chinese: "大腦需要連續不斷地供血。"},
{ID: 825, English: "The doctor's words made him feel comfortable.", Chinese: "醫生的話讓他感覺很舒服。"},
{ID: 826, English: "The truth is quite other than what you think.", Chinese: "事實真相和你所想的完全不同。"},
{ID: 827, English: "They stopped talking when their boss came in.", Chinese: "當老闆進來的時候；他們停止了交談。"},
{ID: 828, English: "They were glad of the examination being over.", Chinese: "他們為考試結束了而高興。"},
{ID: 829, English: "This is by far the largest cake in the world.", Chinese: "這是目前世界上最大的蛋糕了。"},
{ID: 830, English: "Whichever you choose, you won't be satisfied.", Chinese: "不論你選擇哪一個，你都不會滿意。"},
{ID: 831, English: "Will you connect this wire to the television?", Chinese: "你把這根電線和電視機接上好嗎?"},
{ID: 832, English: "His words are strongly impressed on my memory.", Chinese: "他的話深深地銘記在我的心頭。"},
{ID: 833, English: "Is this the right bus for the Capital Library?", Chinese: "這輛車到首都圖書館嗎?"},
{ID: 834, English: "One third of this area is covered with forest.", Chinese: "這一地區三分之一的地方都是森林。"},
{ID: 835, English: "They are arguing over who should pay the bill.", Chinese: "他們為誰應該付款而爭論不休。"},
{ID: 836, English: "Wait a moment, I'll be with you in an instant.", Chinese: "等一下，我立刻就來。"},
{ID: 837, English: "You'll save time not waiting for the elevator.", Chinese: "你可以節省等電梯的時間。"},
{ID: 838, English: "A clear conscience laughs at false accusation.", Chinese: "只要問心無愧，無端的指責可以一笑置之。"},
{ID: 839, English: "I have a headache, and she has a stomachache.", Chinese: "我頭疼，她胃疼。"},
{ID: 840, English: "He glared at Bill, ready to teach him a lesson.", Chinese: "他怒視著比爾，準備教訓他一頓。"},
{ID: 841, English: "I assure you that you will feel no pain at all.", Chinese: "我保證你根本不會覺得疼的。"},
{ID: 842, English: "I can't afford to go to a restaurant every day.", Chinese: "每天都去餐館吃飯,我真是支付不起。"},
{ID: 843, English: "I left at 6:00 so that I could catch the train.", Chinese: "我六點鐘出門,以便趕上火車。"},
{ID: 844, English: "I'm afraid I have some rather bad news for you.", Chinese: "我恐怕有些很壞的消息要告訴你。"},
{ID: 845, English: "Learn to say the right thing at the right time.", Chinese: "學會在適當的時候說適當的話。"},
{ID: 846, English: "No wonder you can't sleep when you eat so much.", Chinese: "你吃這麼多難怪睡不著。"},
{ID: 847, English: "Please ask her to call me back when she's back.", Chinese: "她回來時請讓她給我回個電話。"},
{ID: 848, English: "There are a lot of people in the swimming pool.", Chinese: "游泳池裏擠滿了人。"},
{ID: 849, English: "They have to work hard to support their family.", Chinese: "他們必須努力工作來支援他們的家。"},
{ID: 850, English: "This way, he can kill two birds with one stone.", Chinese: "這樣他就能兩全其美。"},
{ID: 851, English: "We are all taking medicine against the disease.", Chinese: "我們都服藥治療疾病。"},
{ID: 852, English: "Would you please go to a dancing party with me?", Chinese: "請你跟我一起去參加一個舞會好嗎?"},
{ID: 853, English: "He usually drops in at my place on his way home.", Chinese: "他常在回家的路上順便來看我。"},
{ID: 854, English: "His vanity was hurt by their talking so frankly.", Chinese: "他們坦率的談話傷害了他的虛榮心。"},
{ID: 855, English: "How would you go to Beijing, by air or by train?", Chinese: "你怎樣去北京，是乘飛機還是坐火車?"},
{ID: 856, English: "I cannot express how glad I am to hear from him.", Chinese: "我無法表達我接到他的信時有多高興。"},
{ID: 857, English: "If Tom cannot keep his promise, he'll lose face.", Chinese: "如果湯姆不能信守諾言，他就會丟面子。"},
{ID: 858, English: "I'll still love her even if she doesn't love me.", Chinese: "即使她不愛我，我還仍然愛她。"},
{ID: 859, English: "I received an invitation, but I did not accept it.", Chinese: "我收到一份請帖，但沒有接受。"},
{ID: 860, English: "If I were you, I would not be bothered by English.", Chinese: "如果我是你，就不會為英語煩惱了。"},
{ID: 861, English: "If you don't work, you will fail to pass the exam.", Chinese: "如果你不學習，你考試就會不及格。"},
{ID: 862, English: "I'm thinking of hanging the lamp from the ceiling.", Chinese: "我打算把燈吊在天花板上。"},
{ID: 863, English: "It is more important to be healthy than bony slim.", Chinese: "健康永遠比皮包骨頭好。"},
{ID: 864, English: "Long ago, people believed that the world was flat.", Chinese: "很久以前人們相信地球是平的。"},
{ID: 865, English: "Old tunes are sweetest and old friends are surest.", Chinese: "老調最甜美，老友最可靠。"},
{ID: 866, English: "She makes it clear that she doesn't like swimming.", Chinese: "她明確地表示她不喜歡游泳。"},
{ID: 867, English: "The constitution guards the liberty of the people.", Chinese: "憲法保護人民的自由。"},
{ID: 868, English: "The doctor examined the soldier's wound carefully.", Chinese: "大夫仔細檢查了戰士的傷口。"},
{ID: 869, English: "The harder I study, the better my English will be.", Chinese: "我越努力,我的英語就會越好。"},
{ID: 870, English: "The sun was shining and the sky was crystal clear.", Chinese: "陽光閃爍,天空湛藍。"},
{ID: 871, English: "This cellar room is very damp in the rainy season.", Chinese: "這間地下室在雨季非常潮濕。"},
{ID: 872, English: "Computers are becoming a part of our everyday life.", Chinese: "電腦正漸成為我們生活的一部分。"},
{ID: 873, English: "Every man is fool sometimes, but none at all times.", Chinese: "每個人都有愚蠢的時候，但是沒有一個人永遠愚蠢。"},
{ID: 874, English: "He dreamed of traveling to remote South Sea Islands.", Chinese: "他曾夢想到遙遠的南海諸島去旅遊。"},
{ID: 875, English: "How can I climb up that wall! I wish I were a bird!", Chinese: "我怎麼能夠爬得上那堵牆?我要是一隻鳥就好了!"},
{ID: 876, English: "However, Susan has not really made up her mind yet.", Chinese: "然而,蘇珊卻還沒有決定。"},
{ID: 877, English: "I really think a little exercise would do you good.", Chinese: "我真的覺得做點運動對你有好處。"},
{ID: 878, English: "I will never forget the days that I spent with you.", Chinese: "我永遠都不會忘記和你一起度過的日子。"},
{ID: 879, English: "We got a bad headache, and my nose is running.", Chinese: "我頭痛得厲害,還流鼻涕。"},
{ID: 880, English: "Many young girls dream of being a fashion model.", Chinese: "許多年輕女孩夢想成為時裝模特兒。"},
{ID: 881, English: "Most of the earth's surface is covered by water.", Chinese: "大部分的地球表面被水覆蓋著。"},
{ID: 882, English: "Somebody's knocking at the door. I'll answer it.", Chinese: "有人在敲門，我去開。"},
{ID: 883, English: "The number 513 bus will take you to the hospital.", Chinese: "513路車會帶你去醫院。"},
{ID: 884, English: "They celebrated his birthday with a dance party.", Chinese: "他們舉辦舞會來祝賀他的生日。"},
{ID: 885, English: "They misplaced this book under other categories.", Chinese: "他們把它錯放到另一個類別去了。"},
{ID: 886, English: "They played a shameful part in the whole affair.", Chinese: "他們在這一事件中扮演了可恥的角色。"},
{ID: 887, English: "As a matter of fact, he was pretending to be ill.", Chinese: "實際上,他是在裝病。"},
{ID: 888, English: "I will speak against anything I know to be wrong.", Chinese: "我會對所有我認為不對的事情直言不諱。"},
{ID: 889, English: "In spite of the heavy rain, she went to the shop.", Chinese: "儘管下著大雨，她還是去了商店。"},
{ID: 890, English: "No matter what happened, he would not say a word.", Chinese: "不管發生什麼事，他也不會說一句話。"},
{ID: 891, English: "No one knows the location of the hidden treasure.", Chinese: "誰也不知道藏寶地點在哪。"},
{ID: 892, English: "The old lady enjoys a quiet life with her family.", Chinese: "老太太和她的家人安享寧靜的生活。"},
{ID: 893, English: "The population of the city is close to a million.", Chinese: "這個城市的人口接近一百萬。"},
{ID: 894, English: "We are prohibited from smoking on school grounds.", Chinese: "我們被禁止在校園內抽煙。"},
{ID: 895, English: "Growth, however, brings new problems and concerns.", Chinese: "不過，發展也帶來了新的問題和顧慮。"},
{ID: 896, English: "He appears to be your friend but I doubt if he is.", Chinese: "他看上去像是你的朋友，但我懷疑他是否是真心的。"},
{ID: 897, English: "I am so full that I would burst with another bite.", Chinese: "我吃得如此之飽，我感覺我再吃一口肚子就要脹破了。"},
{ID: 898, English: "I have two cats. One is white, the other is black.", Chinese: "我有兩隻貓，一隻是白貓，另一隻是黑貓。"},
{ID: 899, English: "I'm sorry, these 2 books are 3 days overdue.", Chinese: "小姐，對不起，這兩本書已經過期 3天了。"},
{ID: 900, English: "Casper has forgotten falling off his bicycle.", Chinese: "卡思柏早忘掉他從自行車上摔下來這件事了。"},
{ID: 901, English: "Manners are quite different from country to country.", Chinese: "各國的禮儀各不相同。"},
{ID: 902, English: "Not only did I know her, but I was her best friend.", Chinese: "我不僅認識她，還是她最好的朋友。"},
{ID: 903, English: "The best-known movie awards are the Academy Awards.", Chinese: "最著名的電影獎是奧斯卡金像獎。"},
{ID: 904, English: "We've got to do something about the neighbor's dog!", Chinese: "我們得對鄰居的狗採取點行動了!"},
{ID: 905, English: "Will you come and join us for dinner on Sunday?", Chinese: "星期天來和我們共進晚餐好嗎?"},
{ID: 906, English: "Do you think people are a company's greatest wealth?", Chinese: "你認為人是公司最大的財富嗎?"},
{ID: 907, English: "He thinks himself somebody, but we think him nobody.", Chinese: "他自以為是重要人物，但我們覺得他什麼也不是。"},
{ID: 908, English: "I believe I haven't reached the summit of my career.", Chinese: "我相信我還沒有達到事業的巔峰。"},
{ID: 909, English: "It is no matter whether you get there early or late.", Chinese: "你早到晚到都沒有關係。"},
{ID: 910, English: "It's against the rules to handle the ball in soccer.", Chinese: "在足球中以手觸球就是犯規。"},
{ID: 911, English: "The nurse assisted the doctor in the operating room.", Chinese: "護士在手術室協助醫生動手術。"},
{ID: 912, English: "What I do on my own time is nobody else's business.", Chinese: "我在自己時間裏幹什麼，根本不關別人的事。"},
{ID: 913, English: "What I want to do is different from those of others.", Chinese: "我想做的與別人不同。"},
{ID: 914, English: "You forget to write down the date of your departure.", Chinese: "您忘了寫離店日期了。"},
{ID: 915, English: "“I wish I'd known about that rule earlier\", she said.", Chinese: "「我要是早點知道這個規矩就好了!」她說。"},
{ID: 916, English: "Could you tell me your secret for a long, happy life?", Chinese: "你能告訴我你長壽和快樂的秘訣嗎?"},
{ID: 917, English: "He holds a position of great responsibility upon him.", Chinese: "他擔任著一個責任重大的職務。"},
{ID: 918, English: "It is said he has secret love affairs with two women!", Chinese: "據說他背地裏和兩個女人有關係！"},
{ID: 919, English: "Number 235 buses run much more frequently, don't they?", Chinese: "235 路車跑得更勤，是不是?"},
{ID: 920, English: "They are only too delighted to accept the invitation.", Chinese: "他們非常樂意接受邀請。"},
{ID: 921, English: "We are going to have the final examination next week.", Chinese: "我們下周舉行期末考試。"},
{ID: 922, English: "And now medical care helps to keep people live longer.", Chinese: "現在的醫療保健使得人們活得更長。"},
{ID: 923, English: "Do you think you'll be able to go to sleep right away?", Chinese: "你認為你馬上就能睡著嗎?"},
{ID: 924, English: "I am in charge of the company when the manager is out.", Chinese: "經理不在時，我來管理公司。"},
{ID: 925, English: "I borrowed a notebook from Tom and I lent it to Marry.", Chinese: "我從湯姆那兒借了一本筆記本，我又把它借給瑪麗了。"},
{ID: 926, English: "I'm doing some washing and John is cooking dinner.", Chinese: "我正在洗衣服，約翰在做晚飯。"},
{ID: 927, English: "Were there any exciting incidents during your journey?", Chinese: "你們在旅行中有沒有什麼令人激動的事情?"},
{ID: 928, English: "As far as policy is concerned, I have to say something.", Chinese: "談到政策,我得說幾句。"},
{ID: 929, English: "Could you tell me what the maximum weight allowance is?", Chinese: "您能告訴我行李的最大重量限額是多少嗎?"},
{ID: 930, English: "He came out of the library, a large book under his arm.", Chinese: "他夾著本厚書,走出了圖書館。"},
{ID: 931, English: "The brothers differ from each other in their interests.", Chinese: "這幾個兄弟各有所好。"},
{ID: 932, English: "Although we can't see these atoms, they really do exist.", Chinese: "雖然我們看不見原子，但它們的確存在。"},
{ID: 933, English: "I am familiar with the casual atmosphere in the company.", Chinese: "我對公司這種放鬆的氛圍感到很熟悉。"},
{ID: 934, English: "Most people eat, write, and work with their right hands.", Chinese: "大多數人吃飯寫字工作都用右手。"},
{ID: 935, English: "Only by working hard can we succeed in doing everything.", Chinese: "只有努力,才能成功"},
{ID: 936, English: "Take it easy, you will be all right in a couple of days.", Chinese: "別擔心，你兩天之內就會痊癒的。"},
{ID: 937, English: "The Beatles represented part of the spirit of their age.", Chinese: "甲殼蟲樂隊代表了他們時代的部分精神。"},
{ID: 938, English: "There being no one to help me, I had to do it all alone.", Chinese: "因為沒有人幫助我，我不得不獨立完成這項工作。"},
{ID: 939, English: "How much cloth does it take to make a skirt for the girl?", Chinese: "為女孩做一條裙子要用多少布?"},
{ID: 940, English: "With all these mouths to feed, he didn't know what to do.", Chinese: "由於有那麼多人要供養，他不知道怎麼辦才好。"},
{ID: 941, English: "I forgot to prepare the speech I'm supposed to give today.", Chinese: "我忘了準備今天的我該做的演講了。"},
{ID: 942, English: "It's supposed to start at 6:00 sharp, but I doubt it will.", Chinese: "應該是六點整開始的，但是我懷疑不會準時。"},
{ID: 943, English: "On behalf of my company, I would like to welcome you here.", Chinese: "我代表我們公司歡迎你來這裡。"},
{ID: 944, English: "She's been quite different since coming back from America.", Chinese: "從美國回來之後，她改變很大。"},
{ID: 945, English: "Today it is common that women and girls make up in public.", Chinese: "今天，在公共場所看到婦女和姑娘化妝是很普遍的事。"},
{ID: 946, English: "I have to transfer to No.11 bus, but where is the bus stop?", Chinese: "我需要換乘11路公共汽車，但是汽車站在哪兒?"},
{ID: 947, English: "I supposed him to be very clever but he was in fact a fool.", Chinese: "我以為他很聰明，其實他是蠢貨。"},
{ID: 948, English: "The rabbit ran to the woods and did not come back any more.", Chinese: "兔子跑進了森林再也沒有出來了。"},
{ID: 949, English: "Tom and Mary congratulated us on the birth of our daughter.", Chinese: "湯姆和瑪麗為我們女兒的出生向我們表示祝賀。"},
{ID: 950, English: "I can't help eating sweets whenever they are in my presence.", Chinese: "我無論什麼時候一看到甜食就忍不住要吃。"},
{ID: 951, English: "l am vacuuming the floor now and have several shirts to iron.", Chinese: "我正在用真空吸塵器清理地板,還有好幾件襯衫要熨。"},
{ID: 952, English: "I will love you until the seas run dry and the rocks crumble.", Chinese: "我將愛你直到海枯石爛。"},
{ID: 953, English: "There is a broken small old gray stone bridge over the river.", Chinese: "河上有一座破爛不堪的、古老的、灰色的小石橋。"},
{ID: 954, English: "No wonder people say that computers are taking over the world.", Chinese: "難怪有人說電子電腦正漸漸接管世界。"},
{ID: 955, English: "The enormous increase of population will create many problems.", Chinese: "巨大的人口增長將產生很多問題。"},
{ID: 956, English: "There's nothing better for you than plenty of water and sleep.", Chinese: "你最好多喝水多休息。"},
{ID: 957, English: "You should always depend on yourself rather than someone else.", Chinese: "你該依靠你自己，而非別人。"},
{ID: 958, English: "I would like to express to all of you here our sincere welcome.", Chinese: "讓我向在座諸位致以最真摯的歡迎。"},
{ID: 959, English: "Many people prefer living in the country to living in the town.", Chinese: "許多人喜歡住在農村而不喜歡住在城市。"},
{ID: 960, English: "Since I'm here, I'd like to try a typical dish of this country.", Chinese: "既然來了，我想吃這個國家特有的食物。"},
{ID: 961, English: "Walking up and down the stairs would beat any exercise machine.", Chinese: "上下樓梯可比什麼健身器都要好。"},
{ID: 962, English: "Had it not been for the alarm clock she wouldn't have been late.", Chinese: "如果不是因為鬧鐘不響的話，她就不會遲到了。"},
{ID: 963, English: "How ever you may work hard, the boss will not be fully satisfied.", Chinese: "無論你有多努力，老闆總不會完全滿意。"},
{ID: 964, English: "If he had not broken his tooth, he would not be in hospital now.", Chinese: "如果他沒有把牙齒弄壞，現在就不用呆醫院了。"},
{ID: 965, English: "You might as well throw your money away as spend it in gambling.", Chinese: "你與其把錢花在賭博上，不如把它丟掉的好。"},
{ID: 966, English: "Can you put me in the picture about the World Cup Football Match?", Chinese: "你能給我講講關於世界盃足球賽的狀況嗎?"},
{ID: 967, English: "I'm usually just using the search engines to look up information.", Chinese: "我通常只是用搜索引擎找一些資料。"},
{ID: 968, English: "He goes home early everyday for fear that his wife would be angry.", Chinese: "他每天很早就回家,免得老婆生氣。"},
{ID: 969, English: "I regret to inform you that we are unable to offer you employment.", Chinese: "很遺憾地告訴你，我們無法雇用你。"},
{ID: 970, English: "I will continue my learning, though I am tired of learning English.", Chinese: "儘管我很煩英語，我還是要學它。"},
{ID: 971, English: "Li Bai is one of the greatest poets that have ever lived in China.", Chinese: "李白是中國有史以來最偉大的詩人之一。"},
{ID: 972, English: "Many people complain that computers are taking over their jobs.", Chinese: "許多人抱怨說電腦正在接管人的工作。"},
{ID: 973, English: "The cupboards in her kitchen were full of things she did not need.", Chinese: "她廚房的櫥櫃中放滿了她不需要的東西。"},
{ID: 974, English: "What he said did not annoy me much, for I knew he did not mean it.", Chinese: "我並不在乎他所說的，我知道他不是那個意思。"},
{ID: 975, English: "He asked me some personal questions, but I would never answer them.", Chinese: "他問了我幾個個人問題，我根本不願回答。"},
{ID: 976, English: "I don't care where we go as long as we don't have to stand in line.", Chinese: "不管去哪，只要不用站著排隊就行。"},
{ID: 977, English: "She likes Mike a lot, but she doesn't want to get married so early.", Chinese: "她喜歡邁克，但她不想那麼早就結婚。"},
{ID: 978, English: "Why don't you find a job and end this dependence upon your parents?", Chinese: "你為何不找個職業，不再依靠你的父母呢?"},
{ID: 979, English: "Will you please try to find out for me what time the train arrives?", Chinese: "能不能請你幫我查查火車什麼時候到?"},
{ID: 980, English: "A good knowledge of English will improve your chances of employment.", Chinese: "英語好將有助於增加你們的就業機會。"},
{ID: 981, English: "If she finds out you spilled ink on her coat, she'll blow her stack.", Chinese: "如果她發現你在她上衣上灑了墨水,她會大發脾氣的。"},
{ID: 982, English: "I would be very grateful for information about entry to your college.", Chinese: "若能寄給我貴校的入學申請資料我將十分感激。"},
{ID: 983, English: "Mr. Smith knew Jack didn't look at the others because he was nervous.", Chinese: "史密斯先生知道傑克不敢看別人是因為緊張。"},
{ID: 984, English: "On being introduced to somebody, a British person often shakes hands.", Chinese: "英國人被介紹給別人的時候常常和對方握握手。"},
{ID: 985, English: "I want to take a walk along the riverbank, singing my favorite songs.", Chinese: "我想在河邊散步，唱我喜歡的歌。"},
{ID: 986, English: "Many people believe that overweight results from overeating and stress.", Chinese: "很多人認為肥胖超重是因為吃得過多和壓力造成的。"},
{ID: 987, English: "Yet all these things, different as they seem, have one thing in common.", Chinese: "然而所有這些東西，看上去雖不同，但卻有一個共同點。"},
{ID: 988, English: "All my best memories come back clearly to me, some can even make me cry.", Chinese: "所有美好的記憶又在我腦海清晰地浮現了，有些甚至還令我哭泣。"},
{ID: 989, English: "This is the most wonderful day of my life, because I'm here with you now.", Chinese: "今天是我一生中最美好的一天，因為我現在和你在一起。"},
{ID: 990, English: "When I was young, I'd listen to the radio, waiting for my favorite songs.", Chinese: "當我還是個小女孩的時候，我常聽著收音機，等待我最喜歡的歌。"},
{ID: 991, English: "I'm certain he'll go to see the film, because he's bought a ticket.", Chinese: "我肯定他會去看電影的，因為他把票都買好了。"},
{ID: 992, English: "Unfortunately you'll have to pay the fine before you check those books out.", Chinese: "在你借書之前你要先付清罰款。"},
{ID: 993, English: "Hi! You guys keep talking so loudly that I have to speak at the top my voice!", Chinese: "哎! 你們一直這樣大聲講話，我都不得不扯著嗓子說話了。"},
{ID: 994, English: "We should know not only the theory but also how to apply it to practice.", Chinese: "我們不僅要知道理論，還要知道怎樣把理論應用於實踐。"},
{ID: 995, English: "Combining exercise with the diet may be the most effective way to lose weight.", Chinese: "運動與節食結合也許是減肥最有效的途徑。"},
{ID: 996, English: "The maximum weight allowance is 60 kilos per traveler, excluding hand luggage.", Chinese: "每個旅客托運的行李最大重量限額是60公斤，手提行李除外。"},
{ID: 997, English: "You are just putting on a little weight. I believe you'll get that off easily.", Chinese: "你只是稍微胖了些，很快就會恢復的。"},
{ID: 998, English: "In many countries, more and more companies are replacing people with computers.", Chinese: "在許多國家有越來越多的公司使用電子電腦來代替人。"},
{ID: 999, English: "There are mice next to the refrigerator, under the sink and inside the cupboard!", Chinese: "冰箱邊、洗碗槽下，還有櫥櫃裏面都有老鼠!"},
{ID: 1000, English: "Nick did not break his promise, but instead he made his stance clearer than before.", Chinese: "尼克沒有違背承諾，反而比以前更堅定立場。"},
}
